### PR TITLE
Refactor spiker to CBSE

### PR DESCRIPTION
**Pull request by DolceTriade**

### CODE REVIEW

**Comment by DolceTriade** [comment]
Just a glorified copy/paste job. Not really sure how to handle the different speeds for the thinker though. Let me know if this is in line with what you envisioned for CBSE, otherwise I can rewrite it to be.

**Comment by Viech** [comment]
I'll have a look as soon as I can. One could probably add a `ThinkingComponent.UpdateActiveThinker` method for the adaptive think timer though that's arguably overkill for a single purpose.

**Comment by Viech** [comment]
Cherry picked (and modified) ff57dda into 05c33af.

**Comment by Viech** [comment]
Actually, I'll let the commit close this once it reaches master.

**Comment by Viech** [comment]
This PR is now contained in #973 and will be automatically closed when the latter gets merged.

**Pull request closed without merging**
