### PR TITLE
cgame: Update dragoon kill message to denote a claw kill instead of a…

### LINKED ISSUE #1041: Alpha 51: Dragoon kill message needs to be updated from mouth attack to slash attack.

### PR DESCRIPTION
**Pull request by DolceTriade**
… mouth kill.

fix  #1041

### CODE REVIEW

**Comment by illwieckz** [comment]
:+1:

**Comment by illwieckz** [comment]
I edited your comment so merging this PR closes  #1041

**Comment by illwieckz** [comment]
@DolceTriade is it better to merge this to `master` or to `for-0.51.0`?

**Comment by Viech** [comment]
I think we need to put it on a feature branch and test it separately, due to the sensitive nature of the obituary messages. Also to make sure the Dragoon is not using its mouth even if outnumbered and forced into a corner – better safe than sorry!

**Pull request merged**
