### PR TITLE
gameplay: reward players that attack bases

### PR DESCRIPTION
**Pull request by bmorel**
Most played servers, that is, @cu-kai and @sweet235 uses this setting since long. When I implemented it, my servers also used it. So far I've read no complaint about this, so I open this PR to make this the official gameplay.

### CODE REVIEW

**Comment by DolceTriade** [comment]
Lgtm assuming this is the value used on those servers

**Review by cu-kai — APPROVED** [review]
Can confirm I've had this set at 10 since the feature was implemented.

**Comment by slipher** [comment]
The argument against this is that it discourages building forward bases. A failed attempt in addition to losing momentum will also feed the enemy players.

**Comment by cu-kai** [comment]
Agreed with @VReaperV 

Human forward bases are already so fragile most players don't bother building them, as you are almost guaranteed to end up losing BP.

**Comment by bmorel** [comment]
> The argument against this is that it discourages building forward bases. A failed attempt in addition to losing momentum will also feed the enemy players

Well, there is already the momentum gain that makes this a very bad idea. And this setting allows to reward people who do not camp, making the game more dynamic. I think it's especially valuable when one plays aliens, as human bases are very sturdy and dangerous, they often kills the attackers, unlike alien bases.

> I imagine the perception of forward bases is skewed by playing too often against bots, with their omniscience of buildings

I disagree. When there are bots, people traditionally do *not* lack money to attack bases. Until very recently, it was impossible to ask bots to do something, and even like this, it's easy to lure "defenders" out of their base to feed on them.
When it's players that decide to camp, the game basically becomes "wait 10 minutes to get 1000¤ and be able to attack anew" because buildings don't reward.

**Comment by DolceTriade** [comment]
Even when playing humans, building forward bases doesn't work well for Humans. Aliens probably only build minor forward bases for a forward booster and that hasn't been super discouraged by this change.

As it stands, this change has been tested quite extensively and there seems to be a consensus that this definitely makes people more likely to rush (which makes the game more fun...).

**Review by necessarily-equal — APPROVED** [review]
Sounds good to me.

**Comment by bmorel** [comment]
@slipher : do you accept the consensus, or should this be discussed further? Otherwise I'll merge this week end.

**Comment by sweet235** [comment]
lgtm

Btw, when losing an fwd base: you lose the BP, the enemy gains momentum and now some funds. I think the fund gain is the smallest impact of the three.

**Comment by bmorel** [comment]
> Btw, when losing an fwd base: you lose the BP, the enemy gains momentum and now some funds. I think the fund gain is the smallest impact of the three

You forgot to mention that the team loosing the building also looses momentum, but this one is usually a rather minor annoyance, except when you're alien and just unlocked the advanced granger.

**Pull request merged**
