### PR TITLE
Use Sys::Milliseconds instead of level.time for rate-limiting of chat messages

### PR DESCRIPTION
**Pull request by necessarily-equal**
Fixes https://github.com/Unvanquished/Unvanquished/issues/2362.

### CODE REVIEW

**Comment by necessarily-equal** [comment]
CI failure is unrelated, compiles fine locally.

**Comment by slipher** [comment]
Looks like you could get the "real level.time" by doing `level.time + level.pausedTime` (regardless of whether the game is paused). Would rather not start introducing a lot of real time calls since now everything consistently works based on level.time and friends.

**Comment by sweet235** [comment]
LGTM

**Comment by DolceTriade** [comment]
lgtm

**Pull request merged**
