### PR TITLE
When levelshot loading fails fall back to the Tremulous path

### PR DESCRIPTION
**Pull request by slipher**

### CODE REVIEW

**Comment by illwieckz** [comment]
Hmm, at the time I said:

> In that specific case I'm fine with the warning since I already want to print a warning that the default path is not found anyway.

So that's fine I guess.

Is the `Delete unused RMLUI 'data formatters'` commit required for this?

**Comment by illwieckz** [comment]
What were the other formatters for?

**Comment by slipher** [comment]
> What were the other formatters for?

I recall checking some at the time and some had been used in circle menus, while others were unused for 10+ years.

**Review by illwieckz — APPROVED** [review]
I find the `$levelshot` a bit hacky but if that works that's good enough.

I would prefer `${levelshot}` or something like that with an ending markup to remove any ambiguity on the length of the name of the pseudo-variable.

LGTM.

**Comment by slipher** [comment]
> I would prefer `${levelshot}` or something like that with an ending markup to remove any ambiguity on the length of the name of the pseudo-variable.

The feature can't be simulated by replacing `${levelshot}` with any fixed string, so that seems misleading. I think of it as a magic directory.

**Pull request merged**
