### PR TITLE
granger: add credit sound and bite mark when "killing" fire

### PR DESCRIPTION
**Pull request by necessarily-equal**
Fixes https://github.com/Unvanquished/Unvanquished/issues/1925

### CODE REVIEW

**Comment by DolceTriade** [comment]
What's a bite mark?

**Comment by necessarily-equal** [comment]
The bite mark is the indicator in the center of the screen that tells you you did hit something

**Comment by illwieckz** [comment]
I believe we call them “weapon indicator”. I'm not saying it's a better name, but you may find some resources with those keywords.

**Review by DolceTriade — APPROVED** [review]

**Comment by illwieckz** [comment]
Does teamkilling also make the ding sound? If I'm right teamkilling also display the weapon indicator, meaning someone killing a fire may wrongly believe he teamkilled the building he tried to defend?

**Comment by necessarily-equal** [comment]
I think teamkilling never does the ting sound. And buildings never do either. Of course, someone may not know that, but for the record with https://github.com/Unvanquished/Unvanquished/pull/1947 you shouldn't be able to teamkill a building anymore as granger

**Pull request merged**
