### PR TITLE
Show oxygen bar only when the followed player is underwater

### PR DESCRIPTION
**Pull request by necessarily-equal**
It used to be shown when anyone was underwater

### CODE REVIEW

**Comment by necessarily-equal** [comment]
This needs someone to test it as it as I don't have a computer atm.

**Comment by bmorel** [comment]
This does not work, tried on watah-b5.
Also, when spawning underwater the bar does not appear, even this is not related I guess.

**Comment by necessarily-equal** [comment]
Damn. Well first to handle following I should use `cg.predictedPlayerState.clientNum` instead of `cg.clientNum`.

But I don't this is why it didn't work. Would `if ( es->number == cg.predictedPlayerState.clientNum )` work maybe?

**Comment by bmorel** [comment]
According to my testing, adding this patch to the PR:

```
diff --git a/src/cgame/cg_rocket_progressbar.cpp b/src/cgame/cg_rocket_progressbar.cpp
index 012155c91..caac7b026 100644
--- a/src/cgame/cg_rocket_progressbar.cpp
+++ b/src/cgame/cg_rocket_progressbar.cpp
@@ -102,12 +102,6 @@ static float CG_Rocket_GetPlayerOxygenProgress()
 		return lastValue;
 	}
 
-	float overwaterDuration = cg.time - cg.underwaterTime;
-	if ( overwaterDuration < (1.0f - lastValue) * breathAgainDuration )
-	{
-		return lastValue + overwaterDuration / breathAgainDuration;
-	}
-
 	return 0.0f;
 }
```

fix the situation.

**Review by illwieckz — APPROVED** [review]
LGTM, please squash on merging.

**Comment by bmorel** [comment]
I'm closing since superseeding PR has been accepted and merged

**Comment by illwieckz** [comment]
I meant https://github.com/Unvanquished/Unvanquished/pull/2034 lol.

It's fine.

**Pull request closed without merging**
