### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by bmorel**

### CODE REVIEW

**Comment by slipher** [comment]
This is excessively big for a single PR. How about everything pmove-related in a separate one?

**Comment by bmorel** [comment]
Indeed, I merged 3 PRs to do this one.
One was adding some comments on the mover thingies and fixing whitespaces (tabs / spaces stuff): 3 trivial commits.
The 2nd one did only the the cgame removal "less dead code in cgame": 1 trivial commit.
The 3rd, the big one, is the weapon refactoring, could be split but that would not make much sense.

The reason why I merged those 3 PRs/branches is that things started to be quite hairy on my side, when I started cleaning up my PRs, I had exactly 24 branches (just for C++ side, ofc), and since I intend to build a new version of my mod soon, I was trying to ease a bit things: merging several branches is pretty messy.

**Comment by bmorel** [comment]
Ok, I'll remove the pmove commits from this PR then, and will open a new one with just the pmove ones (will need to be on top of this one though I think)

**Comment by bmorel** [comment]
I would like to see this reviewed and merged before downgrading CBSE to vec3_t, as those changes will collide a lot (especially the changes in sg_weapons.cpp)

**Review by necessarily-equal — APPROVED** [review]

**Comment by necessarily-equal** [comment]
I've tested almost every buildable attacks, and human and alien weapon (with the exception of the regular goon bite, all goon pounces, granger slice). I found no regression

**Pull request merged**
