### PR TITLE
[0.52] things to merge at the very last moment

### PR DESCRIPTION
**Pull request by illwieckz**
this branch is meant for things to merge at release time

@slipher, didn't you have some changes to postpone to the very last moment?

See also: https://github.com/DaemonEngine/Daemon/pull/458

### CODE REVIEW

**Comment by slipher** [comment]
I don't think so, that's why we have a 0.52 branch :)

**Comment by illwieckz** [comment]
Hum, I'm like 99.99% sure there was a change that was postponed to the last minute. Maybe that was on engine side…

**Comment by illwieckz** [comment]
Hmmm, maybe you already took care of them, because yes, my memory wasn't wrong, you postponed some things in the past: https://github.com/DaemonEngine/Daemon/pull/223#issuecomment-531077838 😁

I find no remaining `TODO(0.52)` in `0.52.0/sync` though, in both Unvanquished and Dæmon source tree. I hope nothing is left over and we are fine. 🙂

**Comment by illwieckz** [comment]
We may be fine,

`git log -S 'TODO(0.52)'` on Daemon:

```
commit ba646fe263c18e8d7fcfc8b1a5c5192e0dc2bb01
Author: slipher <*****@*****.***>
Date:   Wed Apr 22 22:18:46 2020 -0700

    IPC messages removed in 0.52.0

commit b0cda6c81a3cb856b38e999746f6bedc36590660
Author: slipher <*****@*****.***>
Date:   Sun Dec 22 22:05:37 2019 -0800

    Remove the feature to use "real" file handles in VMs
    
    This is done in order to smooth the way for a migration from NaCl to
    WASM.
    
    PakPath::ReadFile was the only place they are used now, so I
    reimplemented it using the interface to the engine's file handle table.

commit 736bf7fb28443d7a3ab3de61b7d2e1a26d0ec324
Author: slipher <*****@*****.***>
Date:   Thu Sep 12 06:53:38 2019 -0700

    Subdirectory support for PAKSERVER checks
    
    The initial implementation requires the PAKSERVER file to exist in every
    directory with downloadable content. This commit makes a change to the
    download protocol (to be switched on in the next release) which allows
    any prefix of the download URL that ends in '/' to be used as the
    directory to check.

commit 2f1cbf9682eab060b5a50ac2edefca41dbfeee87
Author: slipher <*****@*****.***>
Date:   Sun Apr 7 12:41:32 2019 -0700

    Remove unused "binary message" code

commit d57fcb04db523888cc397213d4dd929584c7b57a
Author: slipher <*****@*****.***>
Date:   Sun Mar 31 07:29:20 2019 -0700

    Remove vestigial code related to drawing fonts from the VM
    
    This functionality no longer is used (or can be used) because UI
    rendering is handled by librocket.
```

`git log -S 'TODO(0.52)'` on Unvanquished:

```
commit 3d1f035cdd08c3948d74524c6baceda34994f553
Author: slipher <*****@*****.***>
Date:   Wed Apr 22 22:16:07 2020 -0700

    Deletions for version 0.52.0

commit aa7e0b8e546ac0379ba3090b37acb031907339a7
Author: slipher <*****@*****.***>
Date:   Sat Jan 26 03:42:38 2019 -0800

    Move parse.cpp (C preprocessor/tokenization library) from engine to
    gamelogic
    
    This code has been located in the engine, but it is only used by the
    gamelogic through trap calls. So it can be moved into the gamelogic and
    the trap calls removed.
    
    Diff of parse.cpp versus the engine version:
    
    diff --git a/daemon/src/engine/qcommon/parse.cpp b/src/shared/parse.cpp
    index 71947a71c..b56bf1d61 100644
    --- a/daemon/src/engine/qcommon/parse.cpp
    +++ b/src/shared/parse.cpp
    @@ -1,28 +1,43 @@
     /*
     ===========================================================================
    +
    +Unvanquished GPL Source Code
     Copyright (C) 1999-2005 Id Software, Inc.
     Copyright (C) 2000-2009 Darklegion Development
    
    -This file is part of Daemon.
    +This file is part of the Unvanquished GPL Source Code (Unvanquished Source Code).
    
    -Daemon is free software; you can redistribute it
    +Unvanquished is free software; you can redistribute it
     and/or modify it under the terms of the GNU General Public License as
     published by the Free Software Foundation; either version 2 of the License,
     or (at your option) any later version.
    
    -Daemon is distributed in the hope that it will be
    +Unvanquished is distributed in the hope that it will be
     useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.
    
     You should have received a copy of the GNU General Public License
    -along with Daemon; if not, write to the Free Software
    +along with Unvanquished; if not, write to the Free Software
     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    +
     ===========================================================================
     */
    
    -#include "qcommon/q_shared.h"
    -#include "qcommon.h"
    +#ifdef BUILD_CGAME
    +#include "cgame/cg_local.h"
    +#else
    +#include "sgame/sg_local.h"
    +#endif
    +
    +static void* Z_Malloc(size_t size)
    +{
    +  return calloc(size, 1);
    +}
    +static void Z_Free(void* ptr)
    +{
    +  free(ptr);
    +}
    
     //script flags
     static const int SCFL_NOERRORS            = 0x0001;
    @@ -47,6 +62,9 @@ static const int TT_FLOAT           = 0x0800; // floating point number
     static const int TT_INTEGER         = 0x1000; // integer number
     static const int TT_LONG            = 0x2000; // long number
     static const int TT_UNSIGNED        = 0x4000; // unsigned number
    +
    +namespace {
    +
     //punctuation sub type
     //--------------------
     enum class punctuationSub_t {
    @@ -224,10 +242,6 @@ struct directive_t
    
     #define DEFINEHASHSIZE 1024
    
    -static bool Parse_ReadToken( source_t *source, token_t *token );
    -static bool Parse_AddDefineToSourceFromString( source_t *source,
    -    char *string );
    -
     int             numtokens;
    
     //list with global defines added to every source loaded
    @@ -309,6 +323,12 @@ punctuation_t   Default_Punctuations[] =
            { nullptr, Util::enum_cast<punctuationSub_t>(0), nullptr }
     };
    
    +} // namespace
    +
    +static bool Parse_ReadToken( source_t *source, token_t *token );
    +static bool Parse_AddDefineToSourceFromString( source_t *source,
    +    char *string );
    +
     /*
     ===============
     Parse_CreatePunctuationTable
    @@ -1143,7 +1163,7 @@ static script_t *Parse_LoadScriptFile( const char *filename )
            void         *buffer;
            script_t     *script;
    
    -       length = FS_FOpenFileRead( filename, &fp, false );
    +       length = trap_FS_FOpenFile( filename, &fp, fsMode_t::FS_READ );
    
            if ( !fp ) { return nullptr; }
    
    @@ -1168,8 +1188,8 @@ static script_t *Parse_LoadScriptFile( const char *filename )
            //
            Parse_SetScriptPunctuations( script, nullptr );
            //
    -       FS_Read( script->buffer, length, fp );
    -       FS_FCloseFile( fp );
    +       trap_FS_Read( script->buffer, length, fp );
    +       trap_FS_FCloseFile( fp );
            //
    
            return script;
```

**Comment by slipher** [comment]
The intent was never to delay something to the last possible moment which would be senseless. It was just a way to batch some changes together so that I did not have to do PRs to both branches every time I did something.

**Comment by illwieckz** [comment]
Yeah, but my brain knew that at some point something was floating in the air, waiting to be done, so my brain configured a trigger for a future that is now a present. 😁

But I did not remembered the details. 🙂

**Pull request merged**
