### PR TITLE
cg_marks: implement `trap_CM_BatchMarkFragments` to process all impact marks in one call

### PR DESCRIPTION
**Pull request by illwieckz**
It requires:

- https://github.com/DaemonEngine/Daemon/pull/1114

It expands:

- https://github.com/Unvanquished/Unvanquished/pull/2847

### CODE REVIEW

**Comment by illwieckz** [comment]
The purpose is to only do a single `trap` call for all marks on the screen at once. This is expected to bring significant performance boost while many players are fighting around, and especially in alien base as alien buildable creep registers an impact mark every frame. Maybe dead bodies do the same too.

**Comment by illwieckz** [comment]
Unfortunately it doesn't work, marks are nto displayed, so I did a mistake somewhere, and I'm looking for help to debug it.

**Comment by illwieckz** [comment]
My `re.MarkFragments` in engine always return `0`…

**Comment by illwieckz** [comment]
I don't get it. I entirely rewrote this branch from scratch, step by step, checking that everything was working on every step.
But as soon as I call `trap_CM_MarkFragmentsArray`, it stops to work.

Even if I copy-paste the original code into `trap_CM_MarkFragmentsArray`, even if I make `trap_CM_MarkFragmentsArray` calling `trap_CM_MarkFragments`.

**Comment by illwieckz** [comment]
The PR is ready, commits will be squashed, no need to review them one by one.

**Comment by slipher** [comment]
LGTM

**Pull request merged**
