### PR TITLE
Firebomb cooldown

### PR DESCRIPTION
**Pull request by sweet235**
Add a cvar `g_firebombCooldown`, that is a time span in milliseconds. Clients can only buy a firebomb after at least this much time has passed since the previous buy. I set this to 2 seconds on my server right now.

I only did this after i have been convinced by multiple persons that we currently have a problem with firebomb spam. Some people (@illwieckz) can regularly be observed standing on armouries and throwing 10 firebombs in a fraction of a second. That makes my poor machine slow and my blind bots burn.

### CODE REVIEW

**Comment by bmorel** [comment]
being able to spam grenades is indeed a problem, and can easily make computers run *very* slowly.

**Comment by slipher** [comment]
I disapprove. There shouldn't be a random purchasing restriction on one item at the armoury that doesn't apply to any of the other items.

https://github.com/Unvanquished/gameplay/issues/58 would be a better way to address this

**Comment by illwieckz** [comment]
Instead of a cooldown on buying, I would set a cooldown on firing as, “no one can fire a second grenade before a given time after a first grenade”. That would be the first objective and reaching it would be enough to counteract the grenade spam hack. I believe there is a consensus on the objective “prevent to spam many grenades in a row without a cooldown” whatever where is the cooldown.

There is also a second objective, but that can be done later, discussed independently, or done at the same time if we agree and this is easier to do both at once. We may even prevent usage of any weapon for the cooldown time… We may actually hide the first person weapon while the grenade countdown is counting (with hope that in the future we would have a first person grenade throw animation to display instead).

**Comment by Viech** [comment]
I agree with the cooldown on firing, unless this needs a new/dedicated netcode field to work; then the server-side solution of a buy timer seems a better fit/less intrusive solution.

**Pull request closed without merging**
