### PR TITLE
add a floating point fudge factor to the floating complain to silence…

### LINKED ISSUE #850: Log spam
Our server has a 110MB daemon.log of this error:
`^3Warn: A resource storage stores an invalid fraction of all build points: 1.0`

It seems to be caused when one or both teams has no drill or leech.

### PR DESCRIPTION
**Pull request by DolceTriade**
… log spam

Fixes #850

### CODE REVIEW

**Comment by DolceTriade** [comment]
Commit message is wrong. I'll merge in the fixed commit message once Viech says this looks good.

**Comment by DolceTriade** [comment]
For some reason, the FLT_EPSILON fudge factor doesn't seem to help.I picked that value because its defined as LINE_EPSILON in q_math.cpp (though not defined publicly).

**Comment by DolceTriade** [comment]
This is an optimization error, since it doesn't happen in Debug mode. 1e-5 is the right fudge factor. Should I declare it as a variable or is it fine as it is?

**Comment by Kangz** [comment]
We might want to keep this in mind when doing floating point asserts too. A constant would be best.

**Comment by Viech** [comment]
Either way, LGTM.

**Comment by DolceTriade** [comment]
Added constant. Will merge now.

**Pull request merged**
