### PR TITLE
Placed daemon-engine in submodule

### PR DESCRIPTION
**Pull request by Elzair**
Since the daemon engine is now being used for multiple projects (such as Xonotic), I think it would be best to place it in its own repository. I used `git filter-branch` to create a repository containing only the commits pertinent to the _daemon_ subdirectory, removed the _daemon_ subdirectory, and added the [new repository](https://github.com/Elzair/daemon-engine) as a submodule under the subdirectory _daemon_. (**NOTE:** Since the _.gitignore_ ignores any files named "daemon", I changed the name to "daemon-engine"). I also removed the submodules _daemon/libs/breakpad_ and _daemon/libs/recastnavigation_ from the repository and added them to the engine repository.

I tested the new system on Arch Linux x86_64. It built okay except for the following part.

`[ 99%] Linking CXX executable cgame-native-exe
CMakeFiles/cgame-native-exe.dir/src/cgame/rocket/rocket.cpp.o: In function`Rocket::Core::Lua::LuaTypeRocket::Core::Lua::Cvar::thunk(lua_State_)':
rocket.cpp:(.text._ZN6Rocket4Core3Lua7LuaTypeINS1_4CvarEE5thunkEP9lua_State[_ZN6Rocket4Core3Lua7LuaTypeINS1_4CvarEE5thunkEP9lua_State]+0x29): undefined reference to `lua_rotate'
rocket.cpp:(.text._ZN6Rocket4Core3Lua7LuaTypeINS1_4CvarEE5thunkEP9lua_State[_ZN6Rocket4Core3Lua7LuaTypeINS1_4CvarEE5thunkEP9lua_State]+0x6e): undefined reference to`lua_rotate'
CMakeFiles/cgame-native-exe.dir/src/cgame/rocket/rocket.cpp.o: In function `Rocket::Core::Lua::LuaTypeRocket::Core::Lua::Cmd::thunk(lua_State_)':
rocket.cpp:(.text._ZN6Rocket4Core3Lua7LuaTypeINS1_3CmdEE5thunkEP9lua_State[_ZN6Rocket4Core3Lua7LuaTypeINS1_3CmdEE5thunkEP9lua_State]+0x29): undefined reference to `lua_rotate'
rocket.cpp:(.text._ZN6Rocket4Core3Lua7LuaTypeINS1_3CmdEE5thunkEP9lua_State[_ZN6Rocket4Core3Lua7LuaTypeINS1_3CmdEE5thunkEP9lua_State]+0x6e): undefined reference to`lua_rotate'
CMakeFiles/cgame-native-exe.dir/src/cgame/rocket/rocket.cpp.o: In function `Rocket::Core::Lua::LuaType<Rocket::Core::Lua::Events>::thunk(lua_State*)':
rocket.cpp:(.text._ZN6Rocket4Core3Lua7LuaTypeINS1_6EventsEE5thunkEP9lua_State[_ZN6Rocket4Core3Lua7LuaTypeINS1_6EventsEE5thunkEP9lua_State]+0x29): undefined reference to`lua_rotate'
CMakeFiles/cgame-native-exe.dir/src/cgame/rocket/rocket.cpp.o:rocket.cpp:(.text._ZN6Rocket4Core3Lua7LuaTypeINS1_6EventsEE5thunkEP9lua_State[_ZN6Rocket4Core3Lua7LuaTypeINS1_6EventsEE5thunkEP9lua_State]+0x6e): more undefined references to `lua_rotate' follow
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cgame-native-exe.dir/build.make:2105: cgame-native-exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:317: CMakeFiles/cgame-native-exe.dir/all] Error 2
[ 99%] Built target cgame-nacl
`

I ran the game, and it seemed to work just fine.

**P.S.** Instead of forking my daemon-engine repository, feel free to upload your own (changing git submodules, of course), and I will fork off of it for future development.

**UPDATE:** Since _daemon/cmake/DaemonCBSE.cmake_ would automatically setup git submodules, I added code in the toplevel _CMakeLists.txt_ that will do likewise.

### CODE REVIEW

**Comment by mbasaglia** [comment]
Some time ago @TimePath experimented with this and we ended up with this repo https://github.com/DaemonDevelopers/Daemon

Yours keeps the history, which is better.

**Comment by mbasaglia** [comment]
I think maybe we should make a new repo within the Unvanquished org (instead of DaemonDevelopers) as it might be a bit easier to manage.

**Comment by Elzair** [comment]
That sounds like the best idea. I will watch this and fork off your repository.

**Comment by mbasaglia** [comment]
Linking your daemon repo here for convenience:
https://github.com/Elzair/daemon-engine

**Comment by mbasaglia** [comment]
Ah never mind it was already linked in the first post :P

**Comment by TimePath** [comment]
Strategy: filter branch up to the split, filter branch after the split, rebase the two together

**Comment by Viech** [comment]
As discussed on IRC, I think sticking with a separate GitHub organization for the engine (e.g. @DaemonDevelopers) makes most sense. We can either collaborate directly on that repository, managing a team of engine developers not linked to any particular game, or projects using the engine as a fork can manage their own teams. Other projects shouldn't be required to contact us at Unvanquished to register new engine developers. A sepertate organization makes the engine also more attractive for developers not associated with any particular game.

**Comment by mbasaglia** [comment]
@Elzair It failed on travis and I got the same error with clone --recursive:
```
$ git clone --recursive git@github.com:Elzair/Unvanquished.git Unv-Split
Cloning into 'Unv-Split'...
remote: Counting objects: 105464, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 105464 (delta 8), reused 0 (delta 0), pack-reused 105448
Receiving objects: 100% (105464/105464), 136.66 MiB | 1.27 MiB/s, done.
Resolving deltas: 100% (74831/74831), done.
Checking connectivity... done.
Submodule 'daemon-engine' (https://github.com/Elzair/daemon-engine3.git) registered for path 'daemon-engine'
Submodule 'libs/libRocket' (https://github.com/Unvanquished/libRocket.git) registered for path 'libs/libRocket'
Submodule 'src/utils/cbse' (https://github.com/DaemonDevelopers/CBSE-Toolchain.git) registered for path 'src/utils/cbse'
Cloning into 'daemon-engine'...
remote: Counting objects: 38458, done.
remote: Compressing objects: 100% (12711/12711), done.
remote: Total 38458 (delta 25692), reused 38458 (delta 25692), pack-reused 0
Receiving objects: 100% (38458/38458), 22.80 MiB | 1.59 MiB/s, done.
Resolving deltas: 100% (25692/25692), done.
Checking connectivity... done.
Submodule path 'daemon-engine': checked out '10b5208a87f5b2d2921bb3dcfacc8521229eeb77'
fatal: no submodule mapping found in .gitmodules for path 'libs/breakpad'
Failed to recurse into submodule path 'daemon-engine'
```

**Comment by Elzair** [comment]
Right now, it is in a state of flux. I have spent some time working on how to better preserve the history. I think [this shell script](https://gist.github.com/Elzair/a86b0cf28061c872b70508f948946e15) should do it. Suggestions are welcome.

**Comment by Elzair** [comment]
Alright, I finally managed to stitch together the repository in a (with hope) satisfactory manner. The repository has history stretching back to [the first commit](https://github.com/Elzair/daemon-engine/commit/681bfb4900b565976d5753aeb97cd052eda5da45), and it contains history for most of the branches (i.e. not just master). I just tested it with the new submodule, and it builds (and plays) just fine. I have not yet tried to build the engine standalone.

**Comment by TimePath** [comment]
Woah, awesome. I (or someone else) will push this to the daemon developers organization, then we can rebase this PR onto cba193984478ddf00ddcdfa42b54599dc030a6b4 with the right repository url (Unvanquished developers may want to point it at a fork)

**Comment by Viech** [comment]
@Kangz and @Amanieu any input on this?

**Comment by Elzair** [comment]
Cool. I actually wrote a "general purpose" (sorta) [tool](https://gist.github.com/Elzair/b6aaf451ca7345423b666d2943b8ec90) to do conversions like these. If you want to do the conversion yourself you can run it with the following options.
`git extract-subdir -b https://github.com/Unvanquished/Unvanquished.git -c ca388dc0c6bac110254a4e5a175abbb7963b1f4f -n -p daemon-engine -s daemon -S "src/common,src/engine,src/libs/crunch,src/libs/detour,src/libs/fastlz,src/libs/findlocale,src/libs/minizip,src/libs/openexr,src/libs/pdcurses,src/libs/recast,src/libs/tinyformat,src/libs/gettext,src/libs/zlib" -v`

**NOTE:** Unvanquishedtmp is the directory of the main Unvanquished re

**Comment by TimePath** [comment]
And updates?

**Comment by mbasaglia** [comment]
@Elzair I've invited you to https://github.com/DaemonDevelopers feel free to overwrite existing branches in https://github.com/DaemonDevelopers/Daemon

Before finalizing and merging this we should wait #939 to be merged (Which is just waiting for review atm) since it makes engine changes.

**Comment by Elzair** [comment]
Cool!

**Comment by mbasaglia** [comment]
IMO we can go ahead.

**Comment by TimePath** [comment]
Please yes. CI is about to get a whole lot faster

**Comment by illwieckz** [comment]
Sorry for the frenchy timecodes:

```
2016-10-11 01:40:22 +0200 <illwieckz>   is that stuff will become a thing on day? https://github.com/Unvanquished/Unvanquished/pull/954
2016-10-11 01:41:18 +0200 <Viech>       it really should
2016-10-11 01:41:55 +0200 <Viech>       kangz and Amanieu may need to give their final blessings as core engine devs and then kharnov and `Ishq […]
2016-10-11 01:42:38 +0200 <`Ishq>       I'm ok with all the changes btw, so don't wait on me.
2016-10-11 02:03:57 +0200 <kharnov>     you know i'm of the opinion that pull requests should never linger
2016-10-11 02:04:02 +0200 <kharnov>     either accept them or close them
2016-10-11 02:04:17 +0200 <`Ishq>       I think all the PRs outstanding look good.
2016-10-11 02:04:22 +0200 <`Ishq>       I just want a 2nd opinion before merging
2016-10-22 15:46:23 +0200 <kharnov>     Amanieu, kangz we're waiting for the two of you to have a consensus on this pull request, can either of you please merge this if you're fine with it? everyone else is: https://github.com/Unvanquished/Unvanquished/pull/954
2016-10-22 15:52:23 +0200 <Amanieu>     I'm fine with it if everyone else is
```

`Ishq got the second opinion he wanted, but it's fair to get the one from @Kangz.

@Elzair will probably have some stuff to double-check since some changes was probably done on the tree.

**Comment by illwieckz** [comment]
See also:

```
2016-08-28 16:35:06 +0200 <kangz>       Melanosuchus : https://github.com/Unvanquished/Unvanquished/pull/954#issuecomment-242961334
2016-08-28 16:35:26 +0200 <kangz>       Exactly why I think we should wait until there is a real need
```

That comment linked by @Kangz [was this one](https://github.com/Unvanquished/Unvanquished/pull/954#issuecomment-242961334), the one from this very thread saying:

> Before finalizing and merging this we should wait #939 to be merged (Which is just waiting for review atm) since it makes engine changes.

PR #939 is now merged so there is probably no need to wait more. @Kangz can you confirm?

**Comment by illwieckz** [comment]
For history:
```
2016-10-24 14:59:37 +0200 <kharnov>	we're going to need a firm decision here
2016-10-24 14:59:44 +0200 <kharnov>	you were the last one we were waiting for so you get to decide
2016-10-24 14:59:55 +0200 <kharnov>	it can't be a "maybe"
2016-10-24 15:00:25 +0200 <kangz>	it can, I have been inactive for some time so I don't think my opinion should count
2016-10-24 15:00:38 +0200 <kangz>	you can go ahead
2016-10-24 15:01:51 +0200 <Amanieu>	just merge it already
2016-10-24 15:02:05 +0200 <Amanieu>	it's been months and nobody has opposed it
```

**Comment by illwieckz** [comment]
I guess the PR has to be redo and the extraction too, to fit current history.

**Comment by mbasaglia** [comment]
Well, @Elzair has access to DaemonDevelopers, so he can use his script to regenerate https://github.com/DaemonDevelopers/Daemon and create a new pull request.

@Elzair, I think you should be the one to go ahead with this since you did most of the job. However, if you don't have time, leave a message and we'll have someone else finish this.

**Comment by Elzair** [comment]
Okay, I will look at this in a bit.

**Comment by illwieckz** [comment]
it's probably better to merge #935 before if it must be merged.

**Comment by mbasaglia** [comment]
To be honest, I'd rather have the split resolved asap. It isn't that hard to repeat changes from outstanding merge requests or migrate branches.

**Comment by Elzair** [comment]
Okay, I will do another repo split.

**Comment by illwieckz** [comment]
Hey guys, I've tried to put my hands on the Daemon split stuff.
This is the [script I wrote](https://gist.github.com/illwieckz/5349570f76ff9e2bb12f802d498bd40c). It preserves history, branches and tags.

The only thing lost is the `.gitmodules`  files since it was outside `daemon/`, but after all it has to be rewritten according to the extraction. So the script rewrites it and readds it to `master`. A `submodule` branch is created for convenience : you just have to merge it to any _Daemon_ branch if needed.

This is the result: https://github.com/illwieckz/Daemon

I can force-push it on https://github.com/DaemonDevelopers/Daemon if it looks OK for you.

**Comment by illwieckz** [comment]
I'm not a CMake master wizard, so I don't know how to add this submodule properly on my own Unvanquished clone to test the compilation. If a gentle people can do this it would be very nice.

**Comment by illwieckz** [comment]
Well no, my script is not good at all, it makes the history starting the day engine stuff has been placed in `daemon/` subdirectory. :weary:

**Comment by illwieckz** [comment]
@Elzair I was fooled by your shell script (I was not able to reproduce things with it) and missed your [ruby based one](https://gist.github.com/Elzair/b6aaf451ca7345423b666d2943b8ec90). I’m trying it. I noticed you use the `--prune-empty` option for `git filter-branch`, every time I used this option it deleted the empty commit even if a tag is attached to. It looks like `git filter-branch` already prune empty commits if they are not merge commit or commit with tags attached to, so using `--prune-empty` looks unsafe.

**Comment by illwieckz** [comment]
@Elzair I've made some intensive tests with your script. For your information, I was not able to get release tags (the `vN.NN.N`) in `master` before modifying your script like that:

```diff
     if subdir == nil
-      self.cmd("filter-branch -- --all")
+      self.cmd("filter-branch #{tagcmd} -- --all")
     elsif subdir.respond_to?('each')
```

Also, all the tags before the split are linked to orphaned commit.

It's easy to check that error: you just have to compare the output of `git branch --contains tags/v0.41.0` and the output of `git branch --contains tags/v0.42.0`. The first one displays nothing, the second one displays all the rewritten branches.

I tried without the `--prune-empty` option and it was not the cause.

Do you have an idea to keep the pre v0.42.0 tags?

_As a side note, it looks like all these orphaned tags make gitg crashing on my end._

**Comment by illwieckz** [comment]
I'm trying a new strategy.

I wrote a script that lists from all branches all previous file names of files that were moved to `daemon/` in commit 38f0b76. This way, I will try to rewrite the whole history moving these old names to `daemon/` in all commits older than the move, then rewrite the whole history to extract only the files in `daemon/`. This way I hope to apply the move to `daemon/` in all commits from the initial one including the initial one. If this trick works, the extraction is the easy part.

**Comment by illwieckz** [comment]
So it looks like to be OK this time.

That is my final strategy:

1. List all files from history (all branches etc.) that lived at least one day under one of these directories:

```
daemon
src/common
src/engine
src/libs/crunch
src/libs/detour
src/libs/fastlz
src/libs/findlocale
src/libs/minizip
src/libs/openexr
src/libs/pdcurses
src/libs/recast
src/libs/tinyformat
src/libs/gettext
src/libs/zlib
```

2. For each one of these files, find all the previous names across all branches

3. Filter the whole history moving all these `previous/paths` to `daemon/previous/paths` if they do not start with `daemon`. With this method there is no need to take care about the commit when the `daemon/` dir were created. Previous commits have `daemon/` prefixes with old paths, later commits have `daemon/` prefixes with new paths if changed.

4. Filter the whole history to extract the `daemon/` directory dropping everything else and stripping that now useless `daemon/` prefix.

This way, even the `daemon/src/engine/renderer/glsl_source/debugShadowMap_fp.glsl` file is there and named `main/glsl/debugShadowMap_fp.glsl` in initial commit.

Have a look at: https://github.com/illwieckz/Daemon/
There is one additional branch: it's the one that just has to be merged in other branches to readd submodules in other branches if needed.

The tags are kept and branches share the same references.

**Comment by illwieckz** [comment]
See my [fast&dirty script](https://github.com/illwieckz/split_unvanquished/blob/master/extract_daemon.sh) to see how it was done. See also this [list](https://github.com/illwieckz/split_unvanquished/blob/master/extract_daemon/list/moved_list.txt) of non `daemon/` files kept in history (there is some other interesting lists to watch).

**Comment by illwieckz** [comment]
To rewrite the DaemonDevelopers' repo with my tree (with all branches, tags etc.):

```sh
illwieckz_remote='git@github.com:illwieckz/Daemon.git'
daemon_remote='git@github.com:DaemonDevelopers/Daemon.git'
git clone --mirror "${illwieckz_remote}" Daemon.git
cd Daemon.git
git push -f --mirror "${daemon_remote}"
```

**Comment by slipher** [comment]
If you rename the files, doesn't that make it impossible to compile any of the old versions?

**Comment by illwieckz** [comment]
_in fine_ they kept the same name.

## before

recent commit:
`daemon/src/engine/renderer/glsl_source/debugShadowMap_fp.glsl`

old commit:
`main/glsl/debugShadowMap_fp.glsl`

## 1st pass: put everything else than `daemon/` sutff on `daemon/` dir

recent commit:
`daemon/src/engine/renderer/glsl_source/debugShadowMap_fp.glsl`

old commit:
`daemon/main/glsl/debugShadowMap_fp.glsl`

## 2nd pass: extract everything from `daemon` dir

recent commit:
`src/engine/renderer/glsl_source/debugShadowMap_fp.glsl`

old commit:
`main/glsl/debugShadowMap_fp.glsl`

when the split to `daemon/` was made it was done the way it can it build from `daemon/`, so it must build on `.` the same way. Older commits kept the same paths as always.

**Comment by illwieckz** [comment]
It means files in commits _before the split_ kept their names, and files in commits _after the split_ just went from `/daemon/` to `/`, keeping the exact same tree. This way this Daemon repository can be added as an Unvanquished submodule as `/daemon/`.

Every commit since the split (since it ensured the engine can be built independently) must be buildable, there is no reason for the contrary except if at this time the build system still needed to have that `daemon` folder living in main repository, and in this case, replacing this Daemon repository on the same revision on both side must work.

By the way in any case the history from Unvanquished repository is left untouched for paleobuilders.

**Comment by illwieckz** [comment]
So, if I build daemon from the extracted repository I can launch the game successfully, same if I readd this daemon repo as unvanquished gitmodule.

I don't think I'm a current member of the @DaemonDevelopers organisation yet. Is someone can add me and give me writing rights on Daemon repository? We are really close to make it ! @mbasaglia, @Viech or @DolceTriade perhaps?

**Comment by Viech** [comment]
@illwieckz I invited you into the Developers team. See if this is sufficient.

**Comment by illwieckz** [comment]
Thanks @Viech. I was able to upload the whole repository. By the way I don't have the permission to change the default repository branch to `master`, can you do it? After that the `daemon` branch would be deletable (it was previous @TimePath attempt).

**Comment by Elzair** [comment]
Cool. I am glad this was done.

**Comment by Viech** [comment]
For the record, the base branch seems to already be set to `master` by the time I'm writing this.

**Comment by Kangz** [comment]
Weird, I thought I commented that I did the base branch change.

**Comment by Viech** [comment]
@Kangz you did, but in the new pull request #983.
@illwieckz next time a short notice in the old pull request for why it's closed would be good to avoid such confusion. 😉

**Comment by illwieckz** [comment]
@Viech, I haven't closed this one myself, it was expected to be closed automatically on #983 merge. ;-)

**Comment by Elzair** [comment]
I closed it because I assumed everything was in place. Would you like me to reopen it?

**Pull request closed without merging**
