### PR TITLE
Round displayed human credits to the lower dozen (1299->1290)

### PR DESCRIPTION
**Pull request by necessarily-equal**
This should be a slight improvement in readability

### CODE REVIEW

**Comment by slipher** [comment]
Why? I don't get it.

**Comment by necessarily-equal** [comment]
I think the last digit is just noise and doesn't bring any actual information. This makes it slightly easier to read in my opinion.

**Comment by slipher** [comment]
Hmm well to me a stuck digit would look bad...

**Comment by Gireen** [comment]
I think that rounding would be weird and create inconsistent results for players. Cause received credits would sometimes be more or less depending on rounding. Its also not more readable imo. 

Despite that, it doesn't hurt to have it optional, with a cvar to enable for whoever wants to use it.

**Comment by necessarily-equal** [comment]
I don't think it would create any noticeable inconsistency: if you kill a dretch all by yourself, you still get +200creds. The rounding happens when you hurt some alien, in which case the number is often really hard to estimate anyway. That's why I don't think there is a sensible loss of information.

**Comment by necessarily-equal** [comment]
I don't want to have an option for this kind of things, the solution is usually to just have a default that works™. If too many people think this is not a good change, let's close this for now. (I still like it though)

**Pull request closed without merging**
