### PR TITLE
cg_particles: add a dedicated logger for particles

### PR DESCRIPTION
**Pull request by illwieckz**
Add a dedicated logger for particles

Trails already have a dedicated logger, Tremulous had a cvar to disable particle logs (and another one for trail logs).

### CODE REVIEW

**Comment by illwieckz** [comment]
Question, what is the difference between:

```c++
static Log::Logger logger("cgame.particles", "[Particle Systems]");
```

and:

```c++
static Log::Logger logger = Log::Logger("cgame.particles", "[Particle Systems]");
```

Various parts of the code base use either first wording or second wording.

**Comment by necessarily-equal** [comment]
I would say the first wording is preferable because it would use only the constructor and not both the constructor and the `operator=` function. It's notvreally important though

**Review by necessarily-equal — APPROVED** [review]
Looked quickly without testing, LGTM

**Comment by slipher** [comment]
LGTM

**Pull request merged**
