### PR TITLE
Replace all uses of <ctype.h> functions with locale-independent versions

### PR DESCRIPTION
**Pull request by slipher**
I was prompted to do this since I was getting some errors from `std::`-prefixed uses of these functions.

In one place (player name validation), I thought it would be better to use a Unicode-aware function to check for spaces, instead of `cisspace`. Is there any existing function for that?

### CODE REVIEW

**Comment by mbasaglia** [comment]
What kind of errors were you getting?

**Comment by DolceTriade** [comment]
With VS2015, if you don't include <cctype> instead of<ctype.h> you can't use the C++ versions. This probably makes part of my vs2015 commits redundant.

**Comment by slipher** [comment]
If you include `cctype` the functions are defined in the `std` namespace. If you include `ctype.h` they are only guaranteed to be in the global namespace.

**Comment by DolceTriade** [comment]
LGTM

**Pull request merged**
