### PR TITLE
Fix confusion about different team numbers related to binds

### LINKED ISSUE #1187: Spectator tutorial fails to get key names from its team (works if global)
See the "follow" bind advice:

[spectator bind](https://dl.illwieckz.net/b/unvanquished/bugs/spectator-bind/unvanquished_2020-04-24_211753_000.jpg)

Note that even as spectator it is displayed correctly when following an human or an alien:

[spectator bind](https://dl.illwieckz.net/b/unvanquished/bugs/spectator-bind/unvanquished_2020-04-24_211814_000.jpg)

This bind works in all case:

```
bind  MOUSE3        +attack3
```

This reproduces the bug:

```
teambind aliens     MOUSE3 +attack3
teambind humans     MOUSE3 itemact grenade
teambind spectators MOUSE3 +attack3
```

This issue is blocking for `0.52`.

### PR DESCRIPTION
**Pull request by slipher**
Fixes #1187.

### CODE REVIEW

**Comment by illwieckz** [comment]
What is making those build bots crazy?

**Comment by slipher** [comment]
> What is making those build bots crazy?

One of those things that only shows up when you build without the precompiled header (which I didn't think was used for gamelogic...).

**Comment by illwieckz** [comment]
I don't know why, but I don't get it working when merged on master, but when I merge it on my `binds/sync` branch it works. Thanks.

**Comment by illwieckz** [comment]
There is still the issue of following players not using (and not displaying) spectator binds. I'm looking at it.

**Comment by slipher** [comment]
> There is still the issue of following players not using (and not displaying) spectator binds.

What do you mean? If you are referring to the situation of being on a team but dead and following teammates, then spectator teambinds cannot be used. Only the binds for the team you are on.

**Comment by illwieckz** [comment]
Yes, the thing is that dead players can follow their teammates, it works. That's why I'm also looking for spectator binds for dead players.

I managed to fix `CG_SetBindTeam` so the tutorial display spectator binds to dead people, but unfortunately the bind does not work.

**Comment by slipher** [comment]
You can't use spectator binds as a dead player. When you are on the alien team, you can only use binds for the alien team and the default team, regardless of whether you're alive. That's working as intended and as it should.

**Comment by illwieckz** [comment]
> That's working […] as it should.

Why? I would like to provide a bind to follow players when I'm dead. Currently it works for aliens but not for humans because they don't have 3rd attack weapon.

**Comment by illwieckz** [comment]
Well… I can imagine player having `vsay` teambinds when following a teammate.

**Comment by slipher** [comment]
The current set of default binds has <kbd>Enter</kbd> for follow. What's wrong with that?

**Comment by illwieckz** [comment]
> The current set of default binds has <kbd>Enter</kbd> for follow. What's wrong with that?

That looks to be a leftover. The code intercepts `useitem` (<kbd>Mouse 3</kbd>) to call `follow`.
The tutorial talk about `useitem` (<kbd>Mouse 3</kbd>) everywhere.

Also <kbd>Mouse 3</kbd> is a very bad key regarding usability: it's far from both left hand (on <kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd>) and right hand (on mouse). The thing is that I'm removing `useitem`.

The key to follow in Unvanquished was is expected to be <kbd>Mouse 3</kbd> and is advertised this way.

---
Note: @Gireen had the idea to make <kbd>Enter</kbd> an alternative bind for global talk. Since you have to put your right hand on keyboard to chat, <kbd>Enter</kbd> is next to right hand when talking.

**Comment by illwieckz** [comment]
> The code intercepts useitem (Mouse 3) to call follow.

Having proper spectator key binds would allow use to remove those hacks (same with `followprev`/`follownext`, to stop abusing `weapprev`/`weapnext`).

But nevermind, that's another job. This PR is ready.

**Comment by illwieckz** [comment]
Just for reference, that is my fix to get spectator key names when following, whatever the team:

[0001-Binds-true-spectator-binds-in-tutorial.patch.txt](https://dl.illwieckz.net/b/unvanquished/wip/true-spectator-binds/0001-Binds-true-spectator-binds-in-tutorial.patch)

It's not enough though, since keys are still reads as human/alien.

**Pull request merged**
