### PR TITLE
g_teamImbalanceWarnings is a boolean, not a duration

### PR DESCRIPTION
**Pull request by bmorel**

### CODE REVIEW

**Comment by slipher** [comment]
I probably broke it by putting the wrong type when migrating it to new-style cvars.

**Comment by bmorel** [comment]
It would be easy enough to make this an integer anew, but anyway is this really useful? I don't think this warning is that useful. The "balance" is just about having the same number of players in both teams, which is obviously wrong, as this does not considers the player's skills at all.

**Comment by DolceTriade** [comment]
Fair enough. LGTM, I don't think making it less spammy is really important. If it is, we can change it back :shrug:

**Comment by slipher** [comment]
This may be closed in favor of #2487

**Comment by bmorel** [comment]
Sure.

**Pull request closed without merging**
