### PR TITLE
Change default wallwalking default smooth value

### PR DESCRIPTION
**Pull request by necessarily-equal**
Fixes https://github.com/Unvanquished/Unvanquished/issues/1389

### CODE REVIEW

**Comment by DolceTriade** [comment]
Can we change this in the UI rather than here?

**Comment by DolceTriade** [comment]
Also I'm not sure medium is the right choice here. https://github.com/Unvanquished/Unvanquished/commit/84d6a234e5756ef8725fda0a8f9c9afad54427b2

I agree with Sixthly here.

**Comment by bmorel** [comment]
> Can we change this in the UI rather than here?

Not really, *this* is actually the UI. This changes the default value, so that the game is more usable for newcommers playing aliens.

> I agree with Sixthly here.

Who? And said what?

**Comment by cu-kai** [comment]
I think medium is too slow. The first thing I always do is set it to fast (at least) if it isn't already. I actually use `cg_wwSmoothTime 50` peresonally.

**Comment by bmorel** [comment]
> I think medium is too slow. The first thing I always do is set it to fast (at least) if it isn't already. I actually use cg_wwSmoothTime 50 peresonally.

Thing is, default configuration should be friendly to *newcommers*. Do you think qualify?

**Comment by bmorel** [comment]
One comment that could be useful considering the UI though: it does not reflects the fact the cvar is an actual number. To set this value to other numbers, people have to know it's a delay-type value, while UI suggest it's only a list-type value. This would be possibly more confusing for new players to have to adjust a number, though.

**Comment by cu-kai** [comment]
> > I think medium is too slow. The first thing I always do is set it to fast (at least) if it isn't already. I actually use cg_wwSmoothTime 50 peresonally.
> 
> Thing is, default configuration should be friendly to _newcommers_. Do you think qualify?

I don't qualify a newcomer, but even when I was all those years ago I found medium very disorientating.

**Comment by bmorel** [comment]
> I don't qualify a newcomer, but even when I was all those years ago I found medium very disorientating.

Wallwalking certainly have this disorienting problem (especially in buggy maps like nano). My opinion, but it's really only mine, is that slower camera moves make it less  disorienting.

**Pull request closed without merging**
