### PR TITLE
Fix crash on cg_shadows modification

### PR DESCRIPTION
**Pull request by slipher**
Fix cvar-related crashes on changing cg_shadows.

This doesn't fix crashes related to uninitialized shaders with certain cg_shadows values.

I have a WIP branch for allowing multiple cvar proxies on one variable (so that multiple modules can observe changes), so I will make sure to fix the underlying cvar system bug with that branch.

### CODE REVIEW

**Comment by slipher** [comment]
Apparently remove the latch flag in the cgame breaks the latching somehow, even if it's latched in the renderer. So this is not ready yet.

**Comment by slipher** [comment]
Switched to a different approach, now it works.

**Comment by illwieckz** [comment]
Yay!

On a side topic, I wonder if we should rename it to `r_shadows`, and it's already named this way in engine code.

This one is very different to `cg_playerShadows` or `cg_buildableShadows`, those is about gameplay stuff : how must be displayed shadows of gameplay elements according to their gameplay kind. But `cg_shadows` is about the way the renderer renders shadow whatever the meaning of what is casting shadow in game.

The `cg_` prefix is probably inherited from 20 years old code, and we are at a time no one we complain if we rename it (we currently only use one value which is the one by default) so it's the perfect time to do a rename. I'm OK to do all the renaming in every repository, and this can be done _after_ this one is merged.

**Comment by slipher** [comment]
OK, rename to r_shadows on 0.53 branches SGTM

**Review by illwieckz — APPROVED** [review]
It works! Thank you very much.

**Pull request merged**
