### PR TITLE
Remove trailing whitespace within src/.

### PR DESCRIPTION
**Pull request by Viech**
Trailing whitespace are annoying to me: If I let my IDE remove them, these changes will end up in commits where they don't belong, complicating the review. If I do not let my IDE remove them, I will add more of them, annoying more people in the long run. With #2622, there is hope that we won't add more of them in the future.

### CODE REVIEW

**Comment by bmorel** [comment]
Usually I just remove them while I edit lines with those, and avoid adding them: I can see those in git's CLI output.
Still, LGTM.

**Comment by DolceTriade** [comment]
Should we add this to `.git-blame-ignore-revs`?

**Comment by DolceTriade** [comment]
(LGTM either way)

**Comment by illwieckz** [comment]
> .git-blame-ignore-revs

good idea

**Comment by Viech** [comment]
File added and confirmed it works with `git blame --ignore-revs-file=.git-blame-ignore-revs`. Haven't added any other commits to it though.

**Review by illwieckz — APPROVED** [review]
LGTM! Make sure the commit id doesn't get rewritten when merging! 😁️

**Comment by Viech** [comment]
> LGTM! Make sure the commit id doesn't get rewritten when merging! grin

If it was possible I'd disable all three "options" that GitHub offers for synchronizing PRs… :grin:

**Pull request merged**
