### PR TITLE
Fix VS2015 builds.

### PR DESCRIPTION
**Pull request by DolceTriade**
Note, this isn't pretty.

### CODE REVIEW

**Comment by mbasaglia** [comment]
Could you explain how and why that makes it work? Maybe it would be useful to have that info as code comments for reference.

Also, appveyor is still failing :-/

**Comment by Kangz** [comment]
+1 on having an explanation, this looks like dark magic currently.

**Comment by DolceTriade** [comment]
I'm pretty sure AppVeyor is failing due to python issues. I'll add comments again in a bit. I'm currently sick of Visual Studio.

**Comment by DolceTriade** [comment]
Obsolete.

**Pull request closed without merging**
