### PR TITLE
Update light.shader

### PR DESCRIPTION
**Pull request by IR4T4**
Fix several light image file references (defaultPointLightShader, defaultProjectedLightShader & defaultDynamicLightShader are no longer initialized as default ;))

### CODE REVIEW

**Comment by DolceTriade** [comment]
File "lights/mkintsquarelight1a.crn" found in "unvanquished_0.25.0.pk3" 

Why is this change necessary?

**Comment by IR4T4** [comment]
I couldn't find the files in this path: https://github.com/Unvanquished/Unvanquished/tree/master/main/lights

**Comment by DolceTriade** [comment]
Ahhh, the files exist in data pk3: http://dl.unvanquished.net/pkg/unvanquished_0.25.0.pk3 which is required to run the game.

**Comment by IR4T4** [comment]
+1: it did really look like a typo. Sorry for the trouble!

**Pull request closed without merging**
