### PR TITLE
True support for old trigger building

### PR DESCRIPTION
**Pull request by bmorel**
fixes all known bugs in trigger_buildable

### CODE REVIEW

**Comment by cu-kai** [comment]
Tested on bunker and confirmed working. This patch is required for the map `mission-control` to work properly.

**Review by DolceTriade — APPROVED** [review]

**Comment by slipher** [comment]
Why are there reverted commits here? Just wasted time reviewing that

**Comment by bmorel** [comment]
that's old stuff I was working on, before changing my mind, while still wanted to have it around for reference I think. Don't worry, I'll squash.

**Review by necessarily-equal — APPROVED** [review]
LGTM, haven't tested.

(For an explaination of why the code was more convoluted, you can see 09f92c95a73349692aacfb2e2437bf84f0b0fb44 where the automatic movers used to be handled differently)

**Pull request merged**
