### PR TITLE
Bots: don't do micro-pounces

### PR DESCRIPTION
**Pull request by necessarily-equal**
Fixes https://github.com/Unvanquished/Unvanquished/issues/2151

### CODE REVIEW

**Comment by necessarily-equal** [comment]
Note 10° is also an acceptable angle. It may be more subtle.

Note also that this may break the usecase where a bot wants to jump on an enemy which has a lower z coord. It would often be broken anyway in that case because the bot would try to jump through the ground, but that's worth a mention.

**Comment by bmorel** [comment]
I'm not fond of magic values. Why 10°? Or 15°?
Was this tested?

**Comment by slipher** [comment]
It looks like when goons are doing movement along the navmesh, they always try to pounce toward `tpos` which is the next path corner. So if it is close, logically they would do a tiny pounce. If I'm right, the correct way to fix it would be not pouncing if `tpos` is too close.

**Comment by bmorel** [comment]
The correct way would be to fix the pounce aiming.

**Comment by bmorel** [comment]
> If I'm right, the correct way to fix it would be not pouncing if tpos is too close.

This would help, yes, probably need to replace pounce in those cases by a jump (since it allows to be faster than walking). Maybe this should be reserved to bots which have `skill >= 6` though (under this, they should just walk?).

**Comment by necessarily-equal** [comment]
superseded by https://github.com/Unvanquished/Unvanquished/pull/2199

**Pull request closed without merging**
