### PR TITLE
Bots use beacons to locate enemy buildables

### PR DESCRIPTION
**Pull request by slipher**
Implement #2641 (the easy alternative <aoeu>#</aoeu>1).

Specifically, this is just for the `closestBuildings` array. There are other ways bots can locate buildables such as BotFindClosestEnemy (which requires being within sense range) that don't depend on this.

I noticed that due to their lower mobility, human bots can take several minutes to find the enemy base on plat23. So I imagine that on larger maps, it could be quite a long time before bots find the enemy base via random roaming. In case this is a problem, what if we give each team one freebie beacon at the start of the game pointing to the enemy's main buildable? It could be useful for flesh-and-blood players too to get oriented a bit quicker in an unfamiliar map. What do you think?

### CODE REVIEW

**Comment by DolceTriade** [comment]
I think the default base beacon SGTM. We could cvar block it if its undesirable in some situations (mods/scenarios/custom layouts/etc)

**Comment by sweet235** [comment]
Using this, we can actually beat the enemy by staring at them.

> what if we give each team one freebie beacon at the start of the game pointing to the enemy's main buildable?

This will fail as soon as the enemy base is moved.

**Comment by slipher** [comment]
Added the starting beacons for enemy main buildables.

**Review by necessarily-equal — APPROVED** [review]
LGTM, haven't tested

**Comment by slipher** [comment]
Is this OK to merge?

**Comment by sweet235** [comment]
This gives us the cartesian product of possible bot bugs and beacon bugs to deal with if a bot fails to attack. I feel like there is at least one bug concerning missing beacons for enemy users/bots, but cannot reproduce it yet.

Bot attacks can be a decisive factor in 1v1 or 2v2. So I hesitate to approve this without scrutiny.

I am running this now.

**Comment by slipher** [comment]
> I have yet to find out how to observe beacons without my observation influencing the beacons.


All right, I made it so that you can use noclip to look at beacons without affecting them.

**Comment by sweet235** [comment]
LGTM

**Pull request merged**
