### PR TITLE
Avoid overwriting submodules during builds

### PR DESCRIPTION
**Pull request by mbasaglia**
Note that there is similar code in Daemon, fixed in DaemonEngine/Daemon/pull/8

### CODE REVIEW

**Comment by DolceTriade** [comment]
I think we need this here to initialize the repo (daemon won't be checked out yet...). Instead, we should figure out why the check is failing. According to the code, it should only initialize the repo if the daemon dir is empty, otherwise, it should do nothing...

**Comment by mbasaglia** [comment]
To be honest I don't think it should be part of the build system at all, it should be done when you check it out and that's it

**Comment by DolceTriade** [comment]
I think that's fair, however, I think it's much easier for developers to get started if stuff magically works for them. We've taken effort to have CMake initialize people's build environment accordingly (ie, with the build_deps tarballs). I think we should maintain this automatic initialization as long as it only happens once and never again.

**Comment by Viech** [comment]
Could also add "Clone instructions" between "Dependencies" and "Build Instructions" in `README.md` (and update the other sections, if necessary). But I generally agree with @DolceTriade that such magic is nice if it's error safe.

**Comment by Viech** [comment]
On this branch, my `daemon` folder is still subject to a forced checkout. See DaemonEngine/Daemon/pull/7. Am I missing something here?

**Comment by illwieckz** [comment]
As @gimhael noticed last month on dev channel, doing:

```
[submodule "daemon"]
	path = daemon
	url = https://github.com/DaemonEngine/Daemon.git
	update = none
```

works too.

I don't know if it's a feature or an ugly workaround by the way.

**Comment by mbasaglia** [comment]
Looks like an ugly workaround to me

**Comment by DolceTriade** [comment]
I am fine with removing submodule init from CMake, or fixing submodule init in CMake. THis leaves everyone else as a tie breaker.

**Comment by slipher** [comment]
This is only for the case where the user just downloaded the repo and forgot to clone --recursive or submodule init, right? If it annoys some people why don't we print a warning telling what command to do instead.

**Comment by DolceTriade** [comment]
I haven't seen this issue. If no one else reports seeing it, I'ma close this PR.

**Comment by Viech** [comment]
Reproduction steps were checking out another commit inside `daemon` and re-running cmake? If so, then I also cannot reproduce.

**Comment by illwieckz** [comment]
Yes that was the reproduction steps.

**Pull request closed without merging**
