### PR TITLE
adds cg_drawPosition: position indicator for the HUD

### PR DESCRIPTION
**Pull request by bmorel**
Requires a change in the UI files to be effective. One problem is, when merged, this will trigger a conflict with RMLUI, hence targeting future 0.54 for now (will need patches, but people will be able to apply this on their local repos if willing to do so).

### CODE REVIEW

**Comment by slipher** [comment]
You can target UI changes to the 0.53 branch, where RmlUi has been merged.

**Comment by bmorel** [comment]
yes, but I want to benefit from it now :)
I still maintain my mod, it have some bugs sometimes, but the features I ask and bring are always related to it, and I'm kind of afraid that 0.53 with the rmlui change will block us for nothing (it's really just about C++14 for what I understand, which is a *bugfix*)

**Comment by slipher** [comment]
Pull requests to the libRocket code (i.e. ones that will create merge conflicts with the RmlUi changes) will not be accepted.

**Comment by bmorel** [comment]
I know, I'm keeping this open for the day we'll be in 0.53. See the target.

**Comment by necessarily-equal** [comment]
Reviving this would need a cleanup and a port to RmlUI

**Pull request closed without merging**
