### PR TITLE
Fix iterate entities

### PR DESCRIPTION
**Pull request by necessarily-equal**
Copy-paste error are evil :(

### CODE REVIEW

**Review by DolceTriade — APPROVED** [review]

**Comment by slipher** [comment]
This makes things worse - it immediately crashes somewhere in BotFindBestEnemy

**Comment by slipher** [comment]
The crash can be produced on NaCl in addition to Windows.

**Review by DolceTriade — CHANGES_REQUESTED** [review]
I'll test it more in depth

**Comment by slipher** [comment]
```
>	sgame-native-dll.dll!Entities::IsAlive(const Entity & entity) Line 43	C++
 	sgame-native-dll.dll!BotEntityIsValidTarget(const gentity_t * ent) Line 1236	C++
 	sgame-native-dll.dll!BotEntityIsValidEnemyTarget(const gentity_t * self, const gentity_t * enemy) Line 1241	C++
 	sgame-native-dll.dll!BotFindBestEnemy(gentity_t * self) Line 814	C++
 	sgame-native-dll.dll!BotSearchForEnemy(gentity_t * self) Line 2242	C++
 	sgame-native-dll.dll!G_BotThink(gentity_t * self) Line 417	C++
 	sgame-native-dll.dll!ClientTimerActions(gentity_t * ent, int msec) Line 890	C++
 	sgame-native-dll.dll!ClientThink_real(gentity_t * self) Line 2232	C++
 	sgame-native-dll.dll!G_RunFrame(int levelTime) Line 2435	C++
 	sgame-native-dll.dll!IPC::detail::HandleMsg<<lambda_7f32fdf8fe614ff2bca8bb9fb4d21dc0>,IPC::Message<IPC::Id<0,9>,int>,IPC::Reply<>>(IPC::Channel & channel, IPC::SyncMessage<IPC::Message<IPC::Id<0,9>,int>,IPC::Reply<>> __formal, Util::Reader reader, VM::VMHandleSyscall::__l7::<lambda_7f32fdf8fe614ff2bca8bb9fb4d21dc0> && func) Line 218	C++
 	sgame-native-dll.dll!IPC::HandleMsg<IPC::SyncMessage<IPC::Message<IPC::Id<0,9>,int>,IPC::Reply<>>,<lambda_7f32fdf8fe614ff2bca8bb9fb4d21dc0>>(IPC::Channel & channel, Util::Reader reader, VM::VMHandleSyscall::__l7::<lambda_7f32fdf8fe614ff2bca8bb9fb4d21dc0> && func) Line 241	C++
 	sgame-native-dll.dll!VM::VMHandleSyscall(unsigned int id, Util::Reader reader) Line 147	C++
 	sgame-native-dll.dll!CommonInit(void * rootSocket) Line 66	C++
 	sgame-native-dll.dll!vmMain(void * rootSocket) Line 104	C++
```

**Pull request closed without merging**
