### PR TITLE
pause empty servers

### LINKED ISSUE #1227: Pause the game at startup until a real player joins
It would be cool if on a server the game is paused at startup until a real player joins. This will save a lot of energy on idling servers.

### PR DESCRIPTION
**Pull request by Gireen**
fix #1227

### CODE REVIEW

**Comment by Gireen** [comment]
well it works as intended except bots disconnect after 4 minutes when the game is paused.
autofill bots reconnect if a client connects to the server.

**Comment by slipher** [comment]
Could it be due to the inactivity timer? For example if you set `g_inactivity 1` (i.e. 1 second) do they get kicked right away?

In any case it seems sensible to disable the activity timer for bots.

**Comment by Gireen** [comment]
no g_inactivity has no effect on the bots. but it was something similar.
in daemon sv_timeout is 240 seconds

**Comment by slipher** [comment]
LGTM, nice and simple implentation.

**Comment by Gireen** [comment]
small additions. now it should work correctly.
(update matchTime that timelimits works, and wait 1 second before pause or else humans win instantly)

**Comment by illwieckz** [comment]
Yay!

**Pull request merged**
