### PR TITLE
make toggleable walls bot obstacles

### PR DESCRIPTION
**Pull request by Gireen**
doesn't work on walls that are spawned on map start

relevant for #1220

### CODE REVIEW

**Comment by necessarily-equal** [comment]
just a style thing: this mixes tabs and spaces in the files it touches.

**Comment by illwieckz** [comment]
I'm not sure to understand what it is about, do you have a simple in-game example?

**Comment by Gireen** [comment]
func_spawn is an object/brush/mapentity that can be toggled. to appear or disappear by a trigger. 
I don't think that this is used in any of our maps so far.
Imagine a box or wall that disappears instantly when a button is pushed and reappears if it is pushed again.
Similar to doors but without moving. But unlike doors bots currently ignore this objects and just try to run trough them. 

With this changes the navmesh is updated when such objects appear or disappear.

**Comment by illwieckz** [comment]
Anything making bots better is welcome! =)

LGTM but I'm not a wizard on such topic.

**Comment by slipher** [comment]
LGTM; I too have no idea how this part of the code works.

How did you run into this issue when there are no maps that use it?

**Comment by Gireen** [comment]
I'm trying mapping and look what interesting things are possible. 
And thereby came up with a [silly method to change maps](https://forums.unvanquished.net/viewtopic.php?f=9&t=2196). 😀

**Comment by necessarily-equal** [comment]
That makes me think… We could have force fields in games! Kinda like 
those in the Darth Maul duel in Star Wars 1 or the cargo bay access to 
space in the USS Tremor alien base.

Le dim 18 oct. 2020 à 20:10, Gireen <notifications@github.com> a 
écrit :

**Pull request merged**
