### PR TITLE
+activate no longer affects doors and buttons

### LINKED ISSUE #2453: `+activate` can be used to open damage entities
How to reproduce: move to door 7 (as close as possible) of map-test-doors, and press the `buy` key as human, the `evolve` key as alien (needs to be big enough, dretches have hard time doing that) or use the command `+activate` : the door will open, while it should not.

This is a behavior that is known about since a long while (since @cu-kai made the test map for damage entities actually), and was used on some very specific instances of damage entities to work around the regression. This regression is no longer alive, and this allows to cheat, so this should be repaired as well.

### PR DESCRIPTION
**Pull request by bmorel**
This fix #2453 but should probably not be merged as is, since I believe this disables something that would be a useful feature if it was handled in a better way and had a good interface. See #2454

### CODE REVIEW

**Comment by bmorel** [comment]
ping @cu-kai , @sweet235

**Comment by bmorel** [comment]
OTOH the code is only disabled, so implementing the feature behind won't generate much conflicts.

**Comment by DolceTriade** [comment]
Can we add a check for damage entities and return early in that case?

**Comment by bmorel** [comment]
superseeded by #2453

**Comment by bmorel** [comment]
Closing because #2469 have testing facilities and has been proven working, so there is no more point in this PR.

**Pull request closed without merging**
