### PR TITLE
Make bot healing fail when medistation is busy

### PR DESCRIPTION
**Pull request by necessarily-equal**
Backport a fix by @bmorel

### CODE REVIEW

**Comment by slipher** [comment]
This could only make sense if the bot is already close to the medistation. If it is far away, then the medistation's current status says little about whether it will be open when the bot arrives.

**Comment by necessarily-equal** [comment]
For the record, this kind of things happen without this, where you can witness most bots waiting to heal while they, or their base, get attacked by aliens.

image
image


Needless to say humans tend to loose fairly quickly when that happens.

**Comment by slipher** [comment]
How about failing the action if the medistation is busy AND the bot's distance from it is less than 200?

**Comment by necessarily-equal** [comment]
> How about failing the action if the medistation is busy AND the bot's distance from it is less than 200?

Should be nice enough. Done

**Comment by slipher** [comment]
LGTM

**Comment by slipher** [comment]
What's wrong with it?

**Comment by bmorel** [comment]
No idea what's wrong with this, except maybe the fact it does not fail if bot is too far :)

For info, the way I use the original feature is to make bot roam in circle around the closer medistat, so the distance check is not really useful.

**Comment by bmorel** [comment]
@necessarily-equal , @slipher I intend to merge this soon (next week) since this PR being a non-merged draft for no reason blocks improvements.
Anything against that?

**Comment by necessarily-equal** [comment]
I would like to keep the BT thing 
(https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/86) 
unmerged until I can check it actually works, but I'd say that we could 
merge this one *with* the "don't fail if too close" reverted — which 
is what I just pushed.

I really think there is a bug lurking in 
https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/86 
though, so I'll have to test.

**Comment by bmorel** [comment]
> "don't fail if too close" reverted

I don't remember having seen such thing. Don't fail if too close would indeed be a bug, since it's definitely possible to have 2 players on a medistation.
Only the check on medistation's target being someone else can mean the medistation is busy, other stuff can only be about it being unpowered (or the distance thing slipher asked for, but that defines a status_running until close enough, so as long as close enough is away enough, things are fine).

> I really think there is a bug lurking in UnvanquishedAssets/unvanquished_src.dpkdir#86 though, so I'll have to test.

I would be curious to see which bug you suspect. The only thing I can see there might be because of changing goals too often, and if it's proven, the fix will be trivial: put the roam in a `decorator delay 2000` block.

**Comment by bmorel** [comment]
Marking this as ready for review, and will merge it on sunday except if there is something more than "suspicion of bug".

**Comment by bmorel** [comment]
@necessarily-equal said "LGTM" on irc.

**Comment by bmorel** [comment]
This has been waiting for more than enough time and received approval from the author anyway.

**Comment by slipher** [comment]
The part about the distance being greater than 200 disappeared. This should be reverted

**Comment by slipher** [comment]
https://github.com/Unvanquished/Unvanquished/commit/48a132e9315145eb44c0aafc7973071df9f3972d is the version I LGTMed

**Comment by bmorel** [comment]
Then I can just add back that patch I guess

**Comment by bmorel** [comment]
I can revert, or #1723 can be merged.

**Comment by necessarily-equal** [comment]
I've removed the distance check from the C++, and said I was ok merging this without the 
distance check because 
https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/86 makes 
it useless anyway. I realize this didn't make it clear I had updated the branch, so sorry for that. However, I believe that if you checkout every branch on master, there is no regression, so there is no need to revert ?

Le 30 janvier 2022 00:09:42 GMT+01:00, "Morel Bérenger" ***@***.***> a écrit :

**Comment by slipher** [comment]
https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/86 does not make the distance check useless.

**Comment by necessarily-equal** [comment]
Could you explain how so?

Le 30 janvier 2022 22:34:18 GMT+01:00, slipher ***@***.***> a écrit :

**Comment by slipher** [comment]
If the distance thing is removed then the healing action fails arbitrarily far from the medistation.

**Comment by bmorel** [comment]
I agree that this is like bots cheating, but the distance suffers the same problems as usual in any cases: don't check walls. Should better do a IsVisible() now that I think about it.
In any cases, the PR I do to sync the submodule do the requested distance change.

**Pull request merged**
