### PR TITLE
rmlui: Fix inconsistent coloring on names after Follow text.

### LINKED ISSUE #2163: Inconsistentency in name colors
Reported by @sweet235 :

### PR DESCRIPTION
**Pull request by DolceTriade**
Fixes #2163

### CODE REVIEW

**Review by illwieckz — APPROVED** [review]
LGTM.

**Comment by necessarily-equal** [comment]
I'm afraid that if people do `^*` it will give something weird. On the plus side, ^* is not documented so in a way nobody expects it works correctly

**Comment by necessarily-equal** [comment]
So I had a doubt and checked. `^*` *is* documented, whoops.

Still better than it was before though

**Comment by DolceTriade** [comment]
I changed from ^* to ^7 so its fine

**Pull request merged**
