### PR TITLE
Cancel votes

### LINKED ISSUE #1940: allow admins to start a vote without voting
Currently, when one starts a vote, it is considered this person if in favor for the change. No way to be neutral.

### LINKED ISSUE #1941: allow to change one's vote
Currently, it is not possible to change one's opinion, which is annoying after discussions.

### PR DESCRIPTION
**Pull request by bmorel**
This PR does 3 things:

1. it makes the G_Vote function less convoluted
2. fixing the vote cancellation system while we're at it
3. allows players to change their mind (i.e. because of a typo or because they were talked into a different point of view)

fix #1941 
fix #1940 as "good enough" since then admins can immediately change their mind (if they allowed that beforehand, but if they're admins...)

### CODE REVIEW

**Comment by bmorel** [comment]
The code is still quite convoluted after this, but it's better, and refactoring this is out of the scope of my PR. There's enough stuff to review as there are, right?

**Comment by sweet235** [comment]
Note: this is not about `/cancelvote`.

**Comment by bmorel** [comment]
> Note: this is not about /cancelvote (I think).

It is not.

**Comment by slipher** [comment]
First commit fixing the config string updating looks good.

The user interface for changing votes may be confusing. If you click "yes", then "no", your vote will be canceled but then if you click "no" a second time, the vote changes to no.

This needs some kind of rate limiting. Currently you can vote arbitrarily often, spamming the users with the vote sound.

**Comment by bmorel** [comment]
> The user interface for changing votes may be confusing. If you click "yes", then "no", your vote will be canceled but then if you click "no" a second time, the vote changes to no.

Agree, but to be honest, I was not expecting to have to do that many changes just for such a basic feature, so I focused on making the cancel vote actually working, since it previously was not.

> Currently you can vote arbitrarily often, spamming the users with the vote sound.

I am aware of this, and this is the reason why I don't propose it as opt-out, but as opt-in. I am not too sure how to do a rate limit that would integrate nicely with the other mechanics like the chat spamming, since this is exactly this that we're talking about.
I also wonder if the problem is not simply that voting emits sound... what does this sound brings, exactly? Why would one care about the fact someone else voted?

**Comment by slipher** [comment]
I took the liberty of pushing the vote counter bug fix commit `fix vote cancelling (and make code readable)` 538a96466e70783b67e21897fe11d4ede9c45c79.

**Comment by bmorel** [comment]
I think you're right, the interface is confusing. But I don't have the strength to work on improving it further, so I'll close this in few days.

**Comment by bmorel** [comment]
will close this this week end

**Comment by bmorel** [comment]
So, before this week end arrives, and it will arrive quickly, let's ask this: is this preferable to current situation or not, considering the fact it is optional?

**Comment by bmorel** [comment]
As promised.

**Pull request closed without merging**
