### PR TITLE
Add tab-completion for the print_momentum command

### PR DESCRIPTION
**Pull request by necessarily-equal**

### CODE REVIEW

**Comment by necessarily-equal** [comment]
See https://github.com/Unvanquished/Unvanquished/blob/master/src/sgame/sg_cmds.cpp#L4538

**Review by DolceTriade — COMMENTED** [review]
How does this work without defining a function for completion?

**Comment by necessarily-equal** [comment]
By telling cgame the function exists

Le 11 septembre 2022 19:30:50 GMT+02:00, DolceTriade ***@***.***> a écrit :
***@***.*** commented on this pull request.

**Comment by slipher** [comment]
LGTM

**Pull request merged**
