### PR TITLE
rocket: unify emoticon class with what people do by hand

### PR DESCRIPTION
**Pull request by illwieckz**
Minor thing, maybe we want to delay the merge to the last minute because it needs a change on `unvanquished_src.dpkdir` side.

See https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/65

### CODE REVIEW

**Comment by slipher** [comment]
Pinging this since the PRs were approved. Won't merge it myself since I don't understand the inter-repo dependencies here.

**Comment by illwieckz** [comment]
I prefer to merge this at the last minute before release, maybe we should create a special tag for that?

**Comment by slipher** [comment]
> I prefer to merge this at the last minute before release

Why would that be needed?

If it is really needed, then the right thing to do is put it on `0.53.0/sync` branches.

**Comment by bmorel** [comment]
I do not think it's useful to delay PRs to 0.53 because of inter-repo relations. Why not just update the children repos, and push this with synced submodules?

**Pull request merged**
