### PR TITLE
Hack to stop undefined symbol error when using SDL2 + VS2015

### PR DESCRIPTION
**Pull request by slipher**

### CODE REVIEW

**Comment by DolceTriade** [comment]
LGTM

**Comment by mbasaglia** [comment]
Will it cause problems if someone builds sdl from source?

I'm not sure if we can detect the sdl abi from cmake but might be worth investigating.

**Comment by DolceTriade** [comment]
It will not cause problems. If they build SDL from source this symbol is extraneous and unused.

**Comment by slipher** [comment]
It's no longer possible to compile anything with the older MSVC anyway.

**Pull request merged**
