### PR TITLE
Add Brazilian Portuguese to language menu

### PR DESCRIPTION
**Pull request by slipher**

### CODE REVIEW

**Comment by DolceTriade** [comment]
I thought we didn't support country suffixes?

Otherwise LGTM

**Comment by slipher** [comment]
> I thought we didn't support country suffixes?

I nuked them from the engine's language auto-detection code, but tinygettext can still interpret them.

**Review by illwieckz — APPROVED** [review]
LGTM.

**Comment by illwieckz** [comment]
This has to be rebased. One can also add the various chinese languages that are now complete.

**Comment by slipher** [comment]
Rebased, and also fixed the Chinese options which were missing from one menu.

**Review by illwieckz — APPROVED** [review]
LGTM again.

**Pull request merged**
