### PR TITLE
Update the readme for new CMake changes

### PR DESCRIPTION
**Pull request by DolceTriade**
- Remove CBSE instructions as they are no longer relevant to building
 - Move Python deps to where the rest of the build deps are.

### CODE REVIEW

**Comment by Kangz** [comment]
LGTM

**Comment by Viech** [comment]
Not looking good yet – all the python stuff is just a buildtime dependency. Those have a section of their own. :stuck_out_tongue:

**Comment by DolceTriade** [comment]
OH yeah... I see what you mean. Will fix.

**Comment by Viech** [comment]
Rebased and merged.

**Comment by dimhotepus** [comment]
Can you, please, add a comment to Wiki about these dependencies for Windows build, too?

`python` ≥ 2,
`python-yaml`,
`python-jinja`

https://wiki.unvanquished.net/index.php?title=Compiling_the_source#Windows

A bit confusing, Wiki has the deps sections for OsX and Linux, but not for Windows.

Written here, because looks like this question is related and do not want to produce new issues.

**Comment by mbasaglia** [comment]
@dimhotepus This is part of a pull request so maybe it's better to open a new issue for this.

**Comment by dimhotepus** [comment]
@mbasaglia ok, i'm new to github flow. Thank you for suggestion. Created a new issue https://github.com/Unvanquished/Unvanquished/issues/913.

**Pull request closed without merging**
