### PR TITLE
Mac continous build on Azure Pipelines

### PR DESCRIPTION
**Pull request by slipher**
See https://github.com/DaemonEngine/Daemon/pull/421 for more information.

### CODE REVIEW

**Comment by slipher** [comment]
I need to fix the branch name for non-PR builds.

**Comment by slipher** [comment]
Got the branch stuff to work finally. @illwieckz does azure_pipelines.yml look good in terms of `git-checkout-modules` usage?

**Comment by illwieckz** [comment]
> illwieckz does azure_pipelines.yml look good in terms of `git-checkout-modules` usage?

That looks OK to me.

**Comment by illwieckz** [comment]
Hmm, one thing that triggers a doubt: `refs/heads/users`.

I know `pull` heads like `pull/1308/head` for pull request, I don't know the `users` one.

If it's about getting PR branch from forks, currently travis and appveyor configuration does not look at them.

**Comment by slipher** [comment]
Yeah, the case where `refs/heads/users/` is stripped probably won't often be useful. I only got started down that route because the documentation gave an example containing it, and failed to mention that the prefix is absent in cases where the source branch is in the same repository.

Maybe it would actually be more logical to use only the target branch in all cases, ignoring the source branch? Like for the case of merging 0.52.0/sync into master, it would be better to check that master build as-is rather than trying to sync any submodules based on the name.

**Comment by illwieckz** [comment]
If I'm right, what we did for the others is that if a PR wants to merge branch A in branch B, we first check for `/sync` in B (and checkout submodules with this branch name if there is) then check for `/sync` in A (and checkout submodules with this branch name if there is).

**Comment by illwieckz** [comment]
> Maybe it would actually be more logical to use only the target branch in all cases, ignoring the source branch?

If I'm right the most important thing is the source branch, for example you make a PR in Unvanquished targeting master with `feature/sync` source branch, you want daemon submodule to be checked out with `feature/sync` too.

The fact we also check for target branch is for having work-in-progress version branches like `0.52.0/sync`.

We can have feature branch targeting version branch, that's why we do both.

**Pull request merged**
