### PR TITLE
listplayers: split the printed count into players and bots

### PR DESCRIPTION
**Pull request by cu-kai**
This now tells people exactly how many real players and how many bots are connected.

### CODE REVIEW

**Comment by DolceTriade** [comment]
output is <real players>, <bots> ( <total players> )?

**Comment by cu-kai** [comment]
> output is `<real players>, <bots> ( <total players> )`?

Exactly

**Review by DolceTriade — APPROVED** [review]

**Comment by slipher** [comment]
`(5 total)` rather than just `(5)` please

**Comment by cu-kai** [comment]
> `(5 total)` rather than just `(5)` please

"total" cannot be translated. I know we have other deficiencies in our translations but I think it's obvious enough what the (total) is. It's only shown when there are bots present.

**Comment by slipher** [comment]
> "total" cannot be translated.

It could if you want. 2 different format strings depending on whether there are bots.

**Comment by cu-kai** [comment]
That does feel like unnecessary code duplication for something as simple as this. Do you consider this blocking?

**Comment by illwieckz** [comment]
(Approved by me)

**Pull request merged**
