### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Unvanquished/Unvanquished](https://hosted.weblate.org/projects/unvanquished/unvanquished/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by bmorel** [comment]
french and breton filenames are wrong, they should be formatted like norvegian ones

**Comment by bmorel** [comment]
Is this issue updated every 12 hours? It constantly appears in my notifications. I'll unsubscribe to it as this just adds noise for no apparent reason.

**Comment by illwieckz** [comment]
> french and breton filenames are wrong, they should be formatted like norvegian ones

The breton one was created by Weblate, so I'll leave it as is.

**Comment by illwieckz** [comment]
Well, it looks like I can't remove the noisy commits of people adding a language and not contributing any translation… 🤨️

Free contrib on GitHub, yay! 🤔️

**Comment by illwieckz** [comment]
We should report a bug to make sure .po files are only added once the first word for the language is translated, not before.

**Comment by illwieckz** [comment]
Also I don't find how to remove the commit removing the language. Anytime someone will add a language without doing any translation we will get noise commits adding and removing them. Letting untranslated languages in the language list on Weblate is likely to destroy the translation statistics.

**Comment by illwieckz** [comment]
So I found a way to reset the repository on Weblate side:  `Manage → Repository maintenance → Maintenance → Reset`

But this does not delete the noise commits on that branch, even if I click `Push` on Weblate. Maybe they will disappear once Weblate force-pushes after a change.

**Comment by illwieckz** [comment]
> Maybe they will disappear once Weblate force-pushes after a change.

That did it.

**Pull request merged**
