### PR TITLE
Revert "make slowblob for advgrangers lockblob"

### PR DESCRIPTION
**Pull request by cu-kai**
This reverts the absurd decision to change granger spit from slowblobs into lockblobs. This gameplay mechanic is **_broken_** and imo should never have been approved in the first place.

### CODE REVIEW

**Comment by cu-kai** [comment]
FYI, changes will be required in https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir such as removing the attribute from configs/weapon/abuild.attr.cfg

**Comment by Gireen** [comment]
The lockblob is really the creation of a madman.  
He must have been completely bonkers adding such a game breaking functions.
The game has become literally unplayable. Servers are only filled with hordes of grangers abusing this cheat like function.
Human player are forced to watch their teammates being destroyed by this savage beasts without any possibility to help.
There is clearly a lack of tools for humans to support each other form afar and kill enemies with some weapon like items.
😄

To prevent such horrible events from happening again we should first discuss gamplay problems, especially controversial topics, in the related issue tracker. 
Freem has already opened an issue for this unvanquished/gameplay#48

**Comment by DolceTriade** [comment]
Was a fun experiment :D

**Comment by bmorel** [comment]
LGTM, but do all other devs agree on the idea of removing this?

**Comment by DolceTriade** [comment]
I'm on board.

**Comment by bmorel** [comment]
Anyone *against* this change?

**Pull request merged**
