### PR TITLE
Jetpack navcons without the hack

### PR DESCRIPTION
**Pull request by sweet235**
This supersedes https://github.com/Unvanquished/Unvanquished/pull/3210. I did not test this yet, but it looks good so far.

### CODE REVIEW

**Comment by slipher** [comment]
LGTM from me, if that counts. I have tested it with one navcon, ensuring that the bot uses the path if and only if it has the jetpack.

`fixup: use polyflags instead of new class/navcon file` was intended to be squashed with the previous commit. Or if we don't squash it it should get a better description.

**Comment by sweet235** [comment]
Do we keep that branch as it is, or do you want to start a new one?

**Comment by slipher** [comment]
Oops, I didn't realize it was my branch. I squashed the commit now.

**Comment by sweet235** [comment]
I propose we merge this as soon as we can. I'll try to review once I am less busy.

We can do later PRs to add whatever else we might need. I think we might want to

- allow specifying the poly flags with the `addcon` command, and
- maybe make some visual distinction between the different flags when looking at the navcons with `navedit`.

**Comment by sweet235** [comment]
It seems the bots without jetpacks are using the jetpack navcons as well. I tested using this navcon file `forlorn-human_naked.navcon`:

```
navcon 3
// armoury up/down
1782 450 3452 1682 130 3338 30 1 63 2
// reactor up/down
1734 130 3077 1825 450 3072 30 1 63 2
```

If I understand the PR correctly, these two navcons are exclusively for jetpack bots, and go in both directions.

To test, I used this behavior file `navcon.bt`:

```
navcon 3
1782 450 3452 1682 130 3338 30 1 63 2
1734 130 3077 1825 450 3072 30 1 63 2
```

And this layout `forlorn/test.dat`:

```
overmind 2888.758057 5010.519531 351.125000 0.000000 89.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000
reactor 1899.209839 3063.589355 452.125000 0.000000 29.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000
eggpod 2759.223389 5010.926758 351.125000 0.000000 97.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000
telenode 1705.163452 3800.223389 452.125000 0.000000 89.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000
medistat 2059.367920 3688.041504 448.125000 0.000000 0.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000
arm 2135.351074 3687.147705 459.424988 0.000000 -10.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000
```

Then I loaded map forlorn, and executed these commands:

```
team h
give momentum 120
set g_momentumHalfLife 9999
set g_freeFundPeriod 1
set g_bot_radarRatio 0
bot add GigaGrise h 5 navcon
```

The bot will buy a jetpack and after a short time, it will fly up to the reactor as expected. We can also use the command `slap GigaGrise 100 0` to make the bot fly up to the medistation.

Then I executed these commands to have a bot without a jetpack:

```
set g_bot_jetpack off
slap GigaGrise 500 0
``` 
I observed that it tried to follow the navcons. Did I do something wrong?

**Comment by sweet235** [comment]
LGTM

**Comment by sweet235** [comment]
The correct navcon file to test is:

```
navcon 3
// armoury up/down
1782 450 3452 1682 130 3338 30 2 63 1
// reactor up/down
1734 130 3077 1825 450 3072 30 2 63 1
```

**Pull request merged**
