### PR TITLE
Drop bot dodge support

### PR DESCRIPTION
**Pull request by necessarily-equal**
The "dodge" mechanism was removed years ago.

### CODE REVIEW

**Comment by slipher** [comment]
This doesn't actually seem to have any relation to double-tap dodge?

**Comment by necessarily-equal** [comment]
I would assume the "dodge" mechanism was implemented as a special class movement (just like the tyrant class movement is running). So that would be why. In any case, it currently is dead code.

**Comment by slipher** [comment]
I checked the history and the code was not changed since it was introduced. BotClassDodge never did anything for humans.

It's not really dead code since it's exposed to the behavior tree scripting language.

**Comment by necessarily-equal** [comment]
I would say that it never was changed, because nobody noticed that it 
wasn't useful anymore. I think when people removed dodge they just 
didn't notice this was left.

**Comment by slipher** [comment]
Nothing was removed from the code this action uses.

> I checked the history and the code was not changed since it was introduced. BotClassDodge never did anything for humans.

**Comment by Gireen** [comment]
Its not useless 😐
Look at what the action does. It lets aliens attack the goal. 
It would probably be good to change the name to something more fitting.

**Comment by necessarily-equal** [comment]
Well, it's not quite useless for aliens, but then it's a bad interface. Goons and tyrants need to charge, and they have no way of doing that. That's why aliens do it in other functions. Like, this action really was designed for the human dodge 😅

Also, I still think it can be considered dead code, as it is never ever called, and I'd be pretty surprised if there is a mod out there calling it

Le 4 novembre 2021 23:16:19 GMT+01:00, Gireen ***@***.***> a écrit :

**Comment by slipher** [comment]
Mind showing your evidence that this is somehow connected to double-tap dodge?

**Comment by necessarily-equal** [comment]
I still don't think this function has any usefulness, but shrug

**Comment by necessarily-equal** [comment]
(It is indeed unrelated to double tab dodge though)

**Pull request closed without merging**
