### PR TITLE
Change the rocket pod acquisition range from 2000 to 1300.

### PR DESCRIPTION
**Pull request by Viech**
See https://github.com/Unvanquished/gameplay/issues/67 for a poll and background on this change.

### CODE REVIEW

**Comment by DolceTriade** [comment]
daemon change seems unrelated? otherwise lgtm

**Comment by Viech** [comment]
Yeah the submodule update wasn't intentional; have removed that.

**Comment by bmorel** [comment]
lgtm

**Comment by sweet235** [comment]
Let's test this. We can increase it again later.

**Review by sweet235 — APPROVED** [review]

**Comment by slipher** [comment]
Any reason not to merge this?

**Pull request merged**
