### PR TITLE
Make underground medistat reachable for human bots

### PR DESCRIPTION
**Pull request by necessarily-equal**
Fixes https://github.com/Unvanquished/Unvanquished/issues/2293

### CODE REVIEW

**Comment by slipher** [comment]
This might break other cases since you don't always have to stand on top of a medistation to use it. If there is an elevated medistation, you can heal by standing against the side of it.

I don't think we should optimize for impossible glitch builds like the one in the operation-dretch layout...

**Comment by necessarily-equal** [comment]
I don't think I got what you mean. Do you mean a slanted medistation?

**Comment by slipher** [comment]
No. Suppose there's a medistation at a human's chest height. He can stand against its edge and heal.

**Comment by slipher** [comment]
I managed to find a spot where the bots will use the medistation from the side, and it still worked with this change.

However, I found that this change can cause a bot to get stuck:
unvanquished_2022-11-05_132400_000

**Comment by necessarily-equal** [comment]
Ok, that likely means tweaking of the height is needed. I'm actually surprised you could build a medistation here because the roof height is really low. What's the map?

**Comment by slipher** [comment]
It's UTCS. And why not? The height is only 6 units.

```
mins        -35 -35 0
maxs        35 35 6
```

**Comment by necessarily-equal** [comment]
The reason I was surprised this is possible is that it is simply impossible to build a medistation under the stairs in chasm. Here's an example in 3rd person view: (the problem also exists in first person view)

image

**Comment by necessarily-equal** [comment]
So I've tried for a bit, and I still can't reproduce your bug where they go above the platform. Anyhow, if they tried to go below the platform it would also be broken. I think in the worst case this isn't a regression because cases that are already broken will still be broken. It improves other cases though.

image

I've pushed a new version that uses the medistation normal as "up", I think it is slightly better for sloped medistations.

**Comment by slipher** [comment]
The normal doesn't affect the medistation's bounding box or mechanics, so I'm not sure it makes sense to use it.

I took a look at the medistation code and and the max healing height is 32 units above the center of the bbox, so it would make sense to use this instead of origin + 50. 

I propose doing a zero-length trace against the elevated goal point, and if it intersects something solid then falling back to the standard goal point. I think with that I would be happy that it won't introduce too many bugs.

**Comment by bmorel** [comment]
The underground medistation thing is a hack, nothing less, nothing more. I do not think bots should support it: they're fragile enough, no need to add more complexity there.

A valid feature request here would be to have bots go heal in healing areas, which is something they can not do. Then, mappers could replace that underground medistation hack with something cleaner, like a heal area reserved to human players, possibly using a medistat model to make it clear for players it's a heal area.

**Pull request closed without merging**
