### PR TITLE
Bot evolve fix and improvement

### PR DESCRIPTION
**Pull request by necessarily-equal**
This fixes the alien bot regression in master and also fixes https://github.com/Unvanquished/Unvanquished/issues/2181.

### CODE REVIEW

**Comment by necessarily-equal** [comment]
#2190

**Comment by necessarily-equal** [comment]
I'm reopening this to help fixing the regression in master faster (see https://github.com/Unvanquished/Unvanquished/pull/2190#issuecomment-1242711261)

**Comment by bmorel** [comment]
I have verified that this fix the regression.

**Comment by slipher** [comment]
LGTM

**Comment by necessarily-equal** [comment]
Merging, as it visibly improves the situation

**Pull request merged**
