### PR TITLE
add more buildable types as rush targets

### PR DESCRIPTION
**Pull request by sweet235**

### CODE REVIEW

**Comment by DolceTriade** [comment]
So what this does is makes bots prioritize some defensive structures instead of just heading for RC/OM + spawns?

**Comment by slipher** [comment]
> So what this does is makes bots prioritize some defensive structures instead of just heading for RC/OM + spawns?

I wouldn't called it "prioritizing" since they only go for those if they don't know the location of any main structure or spawns.

LGTM

**Comment by sweet235** [comment]
> So what this does is makes bots prioritize some defensive structures instead of just heading for RC/OM + spawns?

The actual priority is given in `BotGetEnemyPriority( gentity_t *self, gentity_t *ent )`, see https://github.com/Unvanquished/Unvanquished/pull/2935 for a recent tweak there. This PR only changes what `action rush` in the .bt files does. Currently, `action rush` will fail if the bots do not know of enemy spawns or the main buildable. Making them rush for other buildings too will often make them discover new buildings.

**Review by DolceTriade — APPROVED** [review]

**Comment by DolceTriade** [comment]
Makes sense. Thanks!

**Pull request merged**
