### PR TITLE
gameplay: Allow lgun to zoom

### PR DESCRIPTION
**Pull request by DolceTriade**
Tested on sweet's server for a while.

### CODE REVIEW

**Comment by sweet235** [comment]
It works fine indeed. But I noticed an aesthetic problem on my server. Lasgun and mdriver use different fields of view, but both show 8x as zoom magnitude. Compare:

a
b

Also, I just noticed that the lasgun model is visible on my screenshot, but the mdriver model is not. I have no idea why.

**Comment by sweet235** [comment]
Being a lazy programmer, I thought about simply removing the 8x. But on the other hand, I do not want to do change the rather nice artwork out of laziness.

**Comment by DolceTriade** [comment]
Technically yes, but I was also rather lazy :smile: 

I wouldn't consider this a blocker I hope...

**Comment by Viech** [comment]
Would maybe be good to duplicate the shader and refer to distinct shaders in the code? Then, one can later add a new shader/materials for this without touching the code again. Not a blocker; just a possible improvment.

**Comment by sweet235** [comment]
> I wouldn't consider this a blocker I hope...

I do not consider this to be blocking. I'm just reporting what multiple users told me when I introduced this on my server. Have to admit: I did not notice this myself.

**Comment by sweet235** [comment]
lgtm

**Review by bmorel — APPROVED** [review]

**Pull request merged**
