### PR TITLE
Enable /teamstatus by default

### PR DESCRIPTION
**Pull request by necessarily-equal**
Enabled with a delay of 5s between commands.

### CODE REVIEW

**Comment by DolceTriade** [comment]
lgtm

**Comment by necessarily-equal** [comment]
(CI failure is unrelated)

**Comment by slipher** [comment]
Personally I dislike it

**Comment by DolceTriade** [comment]
My impression is that the majority of the players like it. Server owners who dislike it can disable it of course, but I think it's almost expected now from Unv players.

**Comment by slipher** [comment]
OK, just casting my vote

**Comment by necessarily-equal** [comment]
Ideally I'd make some improved HUD on tab key with minimap and team status and all; but I don't have the time for that at the moment. I think this is a good start in the meantime :smile:

**Comment by sweet235** [comment]
There is another reason for wanting to have this enabled on all servers: we still did not fix the bug that sometimes tells players there is no spawn left, when in fact there is a single spawn left. This is very confusing, and asking /teamstatus will help, as it counts for itself.

> Ideally I'd make some improved HUD on tab key with minimap and team status

I would prefer this too. At least the output of teamstatus is rather pleasant to look at (compared to other text output).

**Comment by DolceTriade** [comment]
> There is another reason for wanting to have this enabled on all servers: we still did not fix the bug that sometimes tells players there is no spawn left, when in fact there is a single spawn left. This is very confusing, and asking /teamstatus will help, as it counts for itself.

What? Was this not fixed by https://github.com/Unvanquished/Unvanquished/issues/2085?

**Comment by sweet235** [comment]
I was not aware of https://github.com/Unvanquished/Unvanquished/issues/2085, otherwise i would have commented on that earlier. I'm quite sure that I saw this bug on my server a few days ago. My server is currently based on master from around 4 weeks ago.

**Comment by sweet235** [comment]
After reading https://github.com/Unvanquished/Unvanquished/issues/2085 carefully, I'm not sure this is the same bug I was talking about.

**Comment by necessarily-equal** [comment]
I think I'll merge this this weekend if nobody has a strong opinion against this. Overall I think it's a good thing, even if I would gladly take a good minimap or hud over this.

**Comment by DolceTriade** [comment]
Sorry, I meant https://github.com/Unvanquished/Unvanquished/commit/045ca800e8852f89cc08382a61a672b3a15325ce

**Pull request merged**
