### PR TITLE
Define bot includes only once

### PR DESCRIPTION
**Pull request by necessarily-equal**
The patch is ugly, but this really just moves D() and D2() directives up.

This should alleviate https://github.com/Unvanquished/Unvanquished/issues/2279, and maybe hopefully fix it.

The bot include code looks terrible though, and getting rid of it would be worthwhile anyhow.

### CODE REVIEW

**Comment by necessarily-equal** [comment]
I've tested bots can still use medkits after this, so it looks like it works.

**Comment by slipher** [comment]
The function doesn't actually run only once.

**Comment by necessarily-equal** [comment]
> The function doesn't actually run only once.

Whoops, I left a `static` out. Fixed

**Comment by slipher** [comment]
LGTM

**Comment by necessarily-equal** [comment]
Note to self: test that this new version still works before merging

**Pull request merged**
