### PR TITLE
More correctness in lastCombatTime update

### PR DESCRIPTION
**Pull request by necessarily-equal**
Found by bmorel
Fixes https://github.com/Unvanquished/Unvanquished/issues/2399.

### CODE REVIEW

**Comment by slipher** [comment]
Not all cases of giving damage really correspond to being "in combat". For example poison and ground flames. In particular it would not make sense that these can make you be "in combat" after you have already died.

**Comment by necessarily-equal** [comment]
Good point, I didn't think it was a problem but that would be a regression indeed

**Comment by necessarily-equal** [comment]
Maybe we should just promote the current behavior to "feature" and forget about it?

**Comment by slipher** [comment]
> Maybe we should just promote the current behavior to "feature" and forget about it?

Works for me

**Comment by bmorel** [comment]
In that case, one of the affectations can be removed, or someone might wonder again why the heck the same variable is affected a value twice, with different names...

**Comment by slipher** [comment]
Cleaning up the double assignment of lastCombatTime in #2875.

**Pull request closed without merging**
