### PR TITLE
Revert ai heal

### LINKED ISSUE #1588: AI try to heal with buildables on ceilings
since #1532, alien AI try to heal 1st with ceiling leeches.
While the idea seems good at first, considering the fact AI don't know the heights, it makes aliens run toward walls endlessly, which is a considerable regression.

### PR DESCRIPTION
**Pull request by bmorel**
fixes #1588

### CODE REVIEW

**Comment by slipher** [comment]
LGTM

**Comment by bmorel** [comment]
> LGTM

Actually it's not: some other commits sneaked in there. The only commit I wanted to get merged is the one which only lets barricade and overmind to be considered worth checking, for the obvious reason that those can only be built on ground.
Let me rebase.

**Comment by bmorel** [comment]
Even with just barricades and overmind, the change is still insufficient. A real revert is likely required.

**Comment by slipher** [comment]
> Even with just barricades and overmind, the change is still insufficient.

How so? They still run into walls or something?

**Comment by bmorel** [comment]
they keep doors open

**Pull request closed without merging**
