### PR TITLE
cmake: Fix the Glob command so that it actually globs the directory

### PR DESCRIPTION
**Pull request by DolceTriade**
Since the syntax was incorrect, the glob wasn't returning the contents
of the directory. Therefore, git submodule update --init --recursive
was being run each time, resetting the submodules.

### CODE REVIEW

**Comment by Viech** [comment]
Should the same be done to daemon, instead of the related commit that sneaked into DaemonEngine/Daemon#8?

**Comment by DolceTriade** [comment]
I don't think so. I think the decision should be left to the parent project. Having it in one location is sufficient.

**Comment by DolceTriade** [comment]
Can I merge?

**Comment by Viech** [comment]
It does not appear to work for me. `cmake` still checks out `heads/master` in the `daemon` submodule:

    ~/src/Unvanquished/build (git)-[fix_submodule_checkout] % LANG=C cmake ..        
    -- git reported v0.50.0-167-gdc5d0ed63+dirty
    -- client
    -- server
    Submodule path 'daemon': checked out 'b6e41f7baae75adbd7121e70d7b73b7e19ec4b6a'
    -- Configuring done
    -- Generating done
    -- Build files have been written to: […]/src/Unvanquished/build

**Comment by mbasaglia** [comment]
Is this "feature" really worth the effort?

**Comment by Viech** [comment]
I'm also not sure if this feature should exist at all. I'd be just as fine with a short readme section on "Getting the source"/"Cloning the repository" that explains the submodule related git commands.

**Comment by DolceTriade** [comment]
Fair enough. It does work for me, but I'd have to debug further on your setup.. We can instead update the readme and tell people to init submodules before building.

**Comment by DolceTriade** [comment]
I'm going to go ahead and merge this since we currently do have this feature anyways. We can always decide to remove it later.

**Comment by illwieckz** [comment]
hu, it does not work at all on my end, and since the "empty dir" detection fails, the submodule is not fetched:

```sh
CMake Error at CMakeLists.txt:52 (add_subdirectory):
  The source directory

    /home/illwieckz/dev/Unvanquished/daemon

  does not contain a CMakeLists.txt file.
```

**Pull request merged**
