### PR TITLE
generate navmeshes for advanced granger, make it climb walls (using navcons)

### PR DESCRIPTION
**Pull request by sweet235**
This works if accompanied by a PR for `res-players` (https://github.com/UnvanquishedAssets/res-players_src.dpkdir/pull/16), where we currently make the advanced granger bots use the same navmeshes as the normal granger. If we give the advanced granger its own navmesh, it can have its own navcons too.

### CODE REVIEW

**Comment by slipher** [comment]
Seems wasteful to generate two identical navcons. Couldn't we make only the navcons need two versions? Or add a flag to the navcons that it requires the advanced granger?

**Comment by sweet235** [comment]
> Seems wasteful to generate two identical navcons.

But consistent and easy to maintain in the future. We are already generating identical navmeshes for dretch and mantis. If someone tries to change either's size, they will not be identical anymore.

> Or add a flag to the navcons that it requires the advanced granger?

Where would we put this flag? The `useNavMesh Granger` in `res-players` is well hidden in a seemingly unrelated file. I would rather avoid something like that.

**Comment by sweet235** [comment]
If we added such a flag, it would be a good idea to make the navcons not depend on a bot's class exclusively. Then we could make bot buy jetpacks, and use seperate navcons reserved only for jetpackers.

**Comment by slipher** [comment]
> But consistent and easy to maintain in the future. We are already generating identical navmeshes for dretch and mantis. If someone tries to change either's size, they will not be identical anymore.

Technically they are not identical now, since the `autojumpSecurity` setting is enabled which makes the step size depend on the jump height, which is different for mantis and dretch. Actually the same thing (different jump heights) is true for the granger types. Still, in either case it seems not worthwhile to me to generate two navmeshes, tiny differences notwithstanding. Especially since dretch/mantis take the longest to generate since they are smaller.

I guess `useNavMesh` could have a 3rd state where it uses the navmesh but not the navcons. If we want to do this, or to have jetpack-specific navcons, I think we would have to create another copy of the navmesh in memory.

**Comment by sweet235** [comment]
I like the idea, but I think hiding this in the model config `res-players` is not appropriate (and very hard to find). Maybe we should simply move this into the C++ source, as many bot settings are not done in config files anyway. What about that?

**Comment by sweet235** [comment]
> Actually the same thing (different jump heights) is true for the granger types

I tried this. To me, the difference seems big enough to create seperate navmeshes, once we make .navcfg files operate per class.

**Comment by slipher** [comment]
> Maybe we should simply move this into the C++ source, as many bot settings are not done in config files anyway. What about that?

Fine with me.

Do you have an opinion on whether dretch and mantis need separate navmeshes?

**Comment by sweet235** [comment]
> Do you have an opinion on whether dretch and mantis need separate navmeshes?

Well, the mantis can jump a lot higher, without any preparation. Simply aim at 45 or 60 degrees upward, and fire its forward pounce. Doing that might make it tolerate a much higher difference between surface and navmesh.

**Comment by slipher** [comment]
> > Do you have an opinion on whether dretch and mantis need separate navmeshes?
> 
> Well, the mantis can jump a lot higher, without any preparation. Simply aim at 45 or 60 degrees upward, and fire its forward pounce. Doing that might make it tolerate a much higher difference between surface and navmesh.

Yeah but that's not taken into account during navgen. Only the difference in standard jumpMagnitude 250 vs 310.

**Comment by sweet235** [comment]
> Yeah but that's not taken into account during navgen. Only the difference in standard jumpMagnitude 250 vs 310.

There is the autojump value, which we could make class-specific. But, as I understand it, there are technical reasons to keep the resulting step size small for dretch and mantis. If we find a way to work around this, there is definitely room for difference in the two mavmeshes.

**Comment by slipher** [comment]
I'm loath to make people in single-player mode generate an Advanced Granger navmesh since they are probably not going to get any benefit from it (no navcons in official assets and this is probably only useful in PvE?). But what if we made a cvar to have some classes share navmeshes for faster generation? Like if the cvar is on, Marauder will use Adv Marauder (marginally larger but same jump height), Mantis will use Dretch (same size but lower jump), and Adv Granger will use Granger (same size for lower jump). We might have this on by default for faster loading in local games but suggest enabling full generation on servers in the sample server config. 

Note that this proposal doesn't change anything about navcons being tied to navmeshes. Any class borrowing another class's navmesh would borrow its navcons too.

**Comment by sweet235** [comment]
> no navcons in official assets

What came first: the chicken or the egg?

> this is probably only useful in PvE?

Not at all. I let my bots build regularly in competetive games. If you are alone in a team against multiple players, what else can you do?  You can do this with `/g_tacticBehaviors "default,build"` and then `/tactic build`. I would make PRs to control where they build, but I think we should have some GUI for bot commands first.

> But what if we made a cvar to have some classes share navmeshes for faster generation

Is the navmesh generation really such a big problem? I always thought the problem is mainly how slow cheap servers are. The few megabytes of disk space for the official maps do not demand to optimize for storage.

We could do such a cvar, and it would probably be more user friendly than hiding that in `res-players`. The navmesh sustitution you describe should be usable in most cases.

**Comment by DolceTriade** [comment]
How much extra time is required to generate navmeshes? I've never felt that navmesh generation has really slowed my load time.

**Comment by sweet235** [comment]
The generation not done as often as the loading. Loading big navmeshes can take some time. But even with all the proposed optimizations, we can only save parts 3 in 11, that is 27%.

**Comment by slipher** [comment]
PTAL at #2905. 

I agree that bot building is useful for non-PvE games; I was talking about granger wallwalking navcons specifically.

About the navmesh generation time, it is not that bad for a non-huge map with a normal PC, but I still like it to be faster. Maybe I am obsessed with loading time to an undue extent.

**Comment by sweet235** [comment]
> What is the lesson to be learned? I am not sure if I am competent to tell that story.

But notice how well we did the automatic navmesh generation, look at this as an instance: https://github.com/Unvanquished/Unvanquished/pull/2909
If we accept to wait for the generation to complete, this is the optimal solution.

**Comment by slipher** [comment]
The advanced granger navmesh is now enabled by #2905.

**Comment by sweet235** [comment]
Am I facing a rogue maintainer?

**Comment by sweet235** [comment]
This is still required. Here is an example map to test whether it works in your branch: https://users.unvanquished.net/~sweet/pkg/map-voxelhill_1.dpk. Use this file `maps/voxelhill-builderupg.navcon`:
```
navcon 3
296 266 1920 216 10 1920 50 1 63 1
296 266 2688 216 10 2688 50 1 63 1
296 266 3456 216 10 3456 50 1 63 1
296 266 4224 216 10 4224 50 1 63 1
296 266 4992 216 10 4992 50 1 63 1
296 266 5760 216 10 5760 50 1 63 1
896 266 1320 896 10 1240 50 1 63 1
1664 266 1320 1664 10 1240 50 1 63 1
1664 266 6872 1664 10 6952 50 1 63 1
2432 266 1320 2432 10 1240 50 1 63 1
2432 266 6872 2432 10 6952 50 1 63 1
3200 266 1320 3200 10 1240 50 1 63 1
3200 266 6872 3200 10 6952 50 1 63 1
3968 266 1320 3968 10 1240 50 1 63 1
3968 266 6872 3968 10 6952 50 1 63 1
4736 266 1320 4736 10 1240 50 1 63 1
4736 266 6872 4736 10 6952 50 1 63 1
5504 266 6872 5504 10 6952 50 1 63 1
5848 266 2688 5928 10 2688 50 1 63 1
5848 266 3456 5928 10 3456 50 1 63 1
5848 266 4224 5928 10 4224 50 1 63 1
5848 266 4992 5928 10 4992 50 1 63 1
5848 266 5760 5928 10 5760 50 1 63 1
5848 266 6528 5928 10 6528 50 1 63 1
552 522 2944 472 266 2944 50 1 63 1
552 522 3712 472 266 3712 50 1 63 1
552 522 4480 472 266 4480 50 1 63 1
552 522 5248 472 266 5248 50 1 63 1
552 522 6016 472 266 6016 50 1 63 1
1664 522 6616 1664 266 6696 50 1 63 1
1920 522 1576 1920 266 1496 50 1 63 1
2432 522 6616 2432 266 6696 50 1 63 1
2688 522 1576 2688 266 1496 50 1 63 1
3200 522 6616 3200 266 6696 50 1 63 1
3456 522 1576 3456 266 1496 50 1 63 1
3968 522 6616 3968 266 6696 50 1 63 1
4224 522 1576 4224 266 1496 50 1 63 1
4736 522 6616 4736 266 6696 50 1 63 1
4992 522 1576 4992 266 1496 50 1 63 1
5592 522 2688 5672 266 2688 50 1 63 1
5592 522 3456 5672 266 3456 50 1 63 1
5592 522 4224 5672 266 4224 50 1 63 1
5592 522 4992 5672 266 4992 50 1 63 1
5592 522 5760 5672 266 5760 50 1 63 1
808 778 2432 728 522 2432 50 1 63 1
808 778 3200 728 522 3200 50 1 63 1
808 778 3968 728 522 3968 50 1 63 1
808 778 4736 728 522 4736 50 1 63 1
808 778 5504 728 522 5504 50 1 63 1
1408 778 1832 1408 522 1752 50 1 63 1
1664 778 6360 1664 522 6440 50 1 63 1
2176 778 1832 2176 522 1752 50 1 63 1
2432 778 6360 2432 522 6440 50 1 63 1
2944 778 1832 2944 522 1752 50 1 63 1
3200 778 6360 3200 522 6440 50 1 63 1
3712 778 1832 3712 522 1752 50 1 63 1
3968 778 6360 3968 522 6440 50 1 63 1
4480 778 1832 4480 522 1752 50 1 63 1
4736 778 6360 4736 522 6440 50 1 63 1
5336 778 2688 5416 522 2688 50 1 63 1
5336 778 3456 5416 522 3456 50 1 63 1
5336 778 4224 5416 522 4224 50 1 63 1
5336 778 4992 5416 522 4992 50 1 63 1
5336 778 5760 5416 522 5760 50 1 63 1
1064 1034 3456 984 778 3456 50 1 63 1
1064 1034 4224 984 778 4224 50 1 63 1
1064 1034 4992 984 778 4992 50 1 63 1
1664 1034 6104 1664 778 6184 50 1 63 1
2432 1034 2088 2432 778 2008 50 1 63 1
2432 1034 6104 2432 778 6184 50 1 63 1
3200 1034 2088 3200 778 2008 50 1 63 1
3200 1034 6104 3200 778 6184 50 1 63 1
3968 1034 2088 3968 778 2008 50 1 63 1
3968 1034 6104 3968 778 6184 50 1 63 1
5080 1034 2688 5160 778 2688 50 1 63 1
5080 1034 3456 5160 778 3456 50 1 63 1
5080 1034 4224 5160 778 4224 50 1 63 1
5080 1034 4992 5160 778 4992 50 1 63 1
1320 1290 2944 1240 1034 2944 50 1 63 1
1320 1290 3712 1240 1034 3712 50 1 63 1
1320 1290 4480 1240 1034 4480 50 1 63 1
1920 1290 2344 1920 1034 2264 50 1 63 1
2432 1290 5848 2432 1034 5928 50 1 63 1
2688 1290 2344 2688 1034 2264 50 1 63 1
3200 1290 5848 3200 1034 5928 50 1 63 1
3456 1290 2344 3456 1034 2264 50 1 63 1
3968 1290 5848 3968 1034 5928 50 1 63 1
4824 1290 3456 4904 1034 3456 50 1 63 1
4824 1290 4224 4904 1034 4224 50 1 63 1
4824 1290 4992 4904 1034 4992 50 1 63 1
1576 1546 3968 1496 1290 3968 50 1 63 1
1576 1546 4736 1496 1290 4736 50 1 63 1
2432 1546 5592 2432 1290 5672 50 1 63 1
2944 1546 2600 2944 1290 2520 50 1 63 1
3200 1546 5592 3200 1290 5672 50 1 63 1
3712 1546 2600 3712 1290 2520 50 1 63 1
4568 1546 3456 4648 1290 3456 50 1 63 1
4568 1546 4224 4648 1290 4224 50 1 63 1
1832 1802 3456 1752 1546 3456 50 1 63 1
1832 1802 4224 1752 1546 4224 50 1 63 1
2432 1802 2856 2432 1546 2776 50 1 63 1
3200 1802 2856 3200 1546 2776 50 1 63 1
3200 1802 5336 3200 1546 5416 50 1 63 1
4312 1802 4224 4392 1546 4224 50 1 63 1
2088 2058 4480 2008 1802 4480 50 1 63 1
3200 2058 5080 3200 1802 5160 50 1 63 1
3456 2058 3112 3456 1802 3032 50 1 63 1
4056 2058 4224 4136 1802 4224 50 1 63 1
2344 2314 3968 2264 2058 3968 50 1 63 1
2944 2314 3368 2944 2058 3288 50 1 63 1
3200 2314 4824 3200 2058 4904 50 1 63 1
3800 2314 4224 3880 2058 4224 50 1 63 1
```

**Review by DolceTriade — APPROVED** [review]

**Comment by slipher** [comment]
LGTM

**Pull request merged**
