### PR TITLE
silence clang warning for bitwise instead of logical operators

### LINKED ISSUE #2652: sg_cmds.cpp: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
This is a warning I get with ICX 2023.1.0 (which is based on very recent LLVM clang):

```
src/sgame/sg_cmds.cpp:3160:9: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
        return Cmd_Sell_upgradeItem( ent, UP_LIGHTARMOUR ) |
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/sgame/sg_cmds.cpp:3160:9: note: cast one or both operands to int to silence this warning
src/sgame/sg_cmds.cpp:3160:9: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
        return Cmd_Sell_upgradeItem( ent, UP_LIGHTARMOUR ) |
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/sgame/sg_cmds.cpp:3160:9: note: cast one or both operands to int to silence this warning
src/sgame/sg_cmds.cpp:3160:9: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
        return Cmd_Sell_upgradeItem( ent, UP_LIGHTARMOUR ) |
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                           ||
src/sgame/sg_cmds.cpp:3160:9: note: cast one or both operands to int to silence this warning
src/sgame/sg_cmds.cpp:3254:10: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
                return Cmd_Sell_weapons( ent ) | Cmd_Sell_upgrades( ent );
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                               ||
src/sgame/sg_cmds.cpp:3254:10: note: cast one or both operands to int to silence this warning
```

_Edit_: I also get this with AOCC 4.0.0 which is based on Clang 14.0.6.

### PR DESCRIPTION
**Pull request by illwieckz**
Fixes #2652:

- https://github.com/Unvanquished/Unvanquished/issues/2652

### CODE REVIEW

**Comment by slipher** [comment]
You should disable the warning in CMake instead.

**Comment by illwieckz** [comment]
But what if someone writes `|` instead of `||` as a mistake one day?

**Comment by slipher** [comment]
Hmm you know what, maybe this code actually is kind of bad and should be changed. Not because of anything with the `|` operator specifically, but rather because it's questionable for any arithmetic or bitwise operator to be used with side-effect-producing expressions on both sides. This is because it's unspecified whether the left or right side evaluates first, so the algorithm is different depending on the compiler's whim. Selling items in a random order is not a bug, but it's preferable not to have unnecessary randomness in the program. We should write it like `bool a = sideEffectProducingExpr1(); bool b = sideEffectProducingExpr2(); return a || b;`

**Comment by illwieckz** [comment]
I prefer that indeed.

**Pull request closed without merging**
