### PR TITLE
Build depends on lua, add it to deps

### PR DESCRIPTION
**Pull request by dimhotepus**
See https://github.com/Unvanquished/Unvanquished/blob/master/CMakeLists.txt#L90
for details.

### CODE REVIEW

**Comment by slipher** [comment]
I think 5.3 is the required version.

**Comment by dimhotepus** [comment]
> I think 5.3 is the required version.

https://github.com/Unvanquished/Unvanquished/blob/master/.travis.yml#L45

Works with 5.2 for me on Debian 4.19.98

**Comment by slipher** [comment]
I recall there being some user reports of errors with an undefined symbol `lua_rotate` (a function added in version 5.3), although I can't find them now. So to check whether it is working, you need to launch the game with the arguments `-set vm.cgame.type 3`, which runs the client gamelogic as a native DLL (since for NaCl and Windows builds a precompiled version is used rather than the system library).

**Comment by dimhotepus** [comment]
> I recall there being some user reports of errors with an undefined symbol `lua_rotate` (a function added in version 5.3), although I can't find them now. So to check whether it is working, you need to launch the game with the arguments `-set vm.cgame.type 3`, which runs the client gamelogic as a native DLL (since for NaCl and Windows builds a precompiled version is used rather than the system library).

```
$ readelf -d cgame-native-dll.so
0x0000000000000001 (NEEDED)             Shared library: [liblua5.2.so.0]
```

```
Loading VM module /home/dimhotepus/github/Unvanquished/cmake-build-debug/cgame-native-dll.so...
Loaded VM module in 13 msec
]Loading Lua interpreter
Loaded font face Roboto Bold (from fonts/Roboto-Bold.ttf).
...
UnnamedPlayer#1 entered the game
```

Playable for me.

**Comment by slipher** [comment]
So we're good to go, thanks for testing.

**Comment by DolceTriade** [comment]
5.3 works. That lua_rotate bug was a bug in CMake.

**Pull request merged**
