### PR TITLE
cgame: better obituaries strings, <3 cu-kai

### PR DESCRIPTION
**Pull request by illwieckz**
Better obituaries strings, see:

- https://github.com/Unvanquished/Unvanquished/pull/2946

### CODE REVIEW

**Review by DolceTriade — COMMENTED** [review]
Would it be better to have emojis here rather than names?

Otherwise LGTM

**Comment by cu-kai** [comment]
If you use capital letters for the class names, I will be happy :smile:

**Comment by illwieckz** [comment]
> If you use capital letters for the class names, I will be happy 😄

To me it looks like capital letters was an unintended side effect of building the string with variables (and variable not having any context about the sentence they are used in), existing strings were already like this:

- `%s%s ^*was incinerated by %s%s%s^*'s firebomb"`
- `"%s%s ^*was gently nibbled by %s%s%s^*'s granger"`

**Comment by illwieckz** [comment]
> Would you prefer it if we didn't use the capital letters?

Yes.

**Review by cu-kai — APPROVED** [review]

**Comment by illwieckz** [comment]
As an exception I will not wait tomorrow to merge this because it fixes wrong strings I merged early in the day and those wrong strings were automatically pushed to weblate and I don't want to waste translator's time who may translate the wrong strings for nothing.

**Comment by NaitLee** [comment]
“player’s tyrant” sounds like “the tyrant that `player` is controlling”, a bit weird, but ok.
Indeed I think all of these are fine. (I don’t mind to re-translate)

```
"%s%s ^*was mauled by %s%s%s^*'s claws"
"%s%s ^*was mauled by %s%s%s^*'s tyrant"
"%s%s ^*was mauled by %s%s%s^*'s Tyrant"
```

And yes, I have capitalized aliens’ names in my translations because I thought they are just names and that’s consistent in a Chinese paragraph. I should (or I must) eventually give them meaningful Chinese names for sure, so that majority of players could understand them.

**Comment by illwieckz** [comment]
> “player’s tyrant” sounds like “the tyrant that `player` is controlling”, a bit weird, but ok.

Yeah, right now it's the expected meaning.

**Comment by illwieckz** [comment]
If it's more consistent with chinese language to capitalize this in chinese it's fine. Sometime capitalization is language specific. For example in English we say « in English » (capitalized), but in French we say « en français » (not capitalized). I guess you'll know better what to do for Chinese and also in the end it's better if all sentences are consistent together for a single language (even if two options are possible for the same language).

**Pull request merged**
