### PR TITLE
Bot BT: add hysteresis node support

### PR DESCRIPTION
**Pull request by necessarily-equal**
Bots have terrible remembrance of the past. One way we do currently add some persistance is with a `sequence { condition (x>300); action }`, but it has the terrible downside of continuing the action until the bot dies, or the action succeed or fail. This will allow for finer grained control where one can tell the bot to do an action *until* the score value goes down, or the action succeeds.

Tested with the following BT (designed for human bots only):
```javascript
selector
{
        hysteresis 100 300 distanceTo( E_H_MEDISTAT )
        {
                action moveTo( E_H_MEDISTAT )
        }

        action moveTo( E_A_OVERMIND )
}

```

@bmorel hopefully you'll like it a lot

### CODE REVIEW

**Comment by Gireen** [comment]
Whats the difference to a normal condition?
```
selector
{
        condition ( distanceTo( E_H_MEDISTAT ) > 100 && distanceTo( E_H_MEDISTAT ) < 300 )
        {
                action moveTo( E_H_MEDISTAT )
        }

        action moveTo( E_A_OVERMIND )
}
```

**Comment by necessarily-equal** [comment]
One question left to answer is: should we reset the hysteresis for a bot when the action failed or succeeded? I would tend to say yes, but this is harder than you would think.

**Comment by necessarily-equal** [comment]
@Gireen: in your example, if the distance is greater than 300, the bot will go to the overmind, while in mine, the bot will go to the medipad, so it is different.

To explain better how it works:
* if a bot is further than 300, it will always go back
* if a bot is closer than 100, it will always go forward
* if a bot is at a distance between 100 and 300, it will continue doing what it was doing (going back if it was going back, going forward if it was going forward.

**Comment by slipher** [comment]
I don't understand the intended semantics of the example.


>    if a bot is further than 300, it will always go back
>    if a bot is closer than 100, it will always go forward
>    if a bot is at a distance between 100 and 300, it will continue doing what it was doing (going back if it was going back, going forward if it was going forward.

Which way is "back" and which way is "forward"?
What happens if the distance is between 100 and 300 at the beginning?

**Comment by bmorel** [comment]
Is there is any use case for that? I'm failing to see the point, I'm afraid.

**Comment by necessarily-equal** [comment]
I've thought about this for some time, and I think this is quite similar to

```js
sequence {
    condition (distanceTo(E_A_OVERMIND) > 700)
    condition (distanceTo(E_A_OVERMIND) > 400) {
        action moveTo(E_A_OVERMIND)
    }
}
```

So this makes this branch not justified enough to stay open I think

**Pull request closed without merging**
