### PR TITLE
always display player name in beacon

### PR DESCRIPTION
**Pull request by Gireen**
independent of team

### CODE REVIEW

**Comment by illwieckz** [comment]
can you make a screenshot?

**Comment by slipher** [comment]
I don't think this information should be available to enemies.

**Comment by Gireen** [comment]
@illwieckz 🤔 on the right side
name

@slipher why? what tactical benefit does it give to enemys? It is also common for shooters that you can see names of the opponents.

**Comment by DolceTriade** [comment]
You can avoid better players.

**Comment by illwieckz** [comment]
If I'm right, in your screenshot the opponent's health is disclosed.

If we want to display player information (name, health, weapon) in beacon, I think it would be better to limit it to team mates.

Unlike usual shooters, Unvanquished is a _strategic_ shooter, and _information_ is a whole battlefield per se.

**Comment by Gireen** [comment]
I mean the beacon text on the right side in this case `[B]Gireen`.
Normal it would say Food instead. And from the human view it shows the alien class name.

This change would only show the name instead these placeholders. 

An other option is to show the name only when seeing the enemy direct with the crosshair instead a beacon with the current position. Like `[B]EmperorJack` in the image but without health.

Its also common for Tactical Shooters and RTS/FPS mixed games to see the name of enemy players. Like Battlefield, Enemy Territory: Quake Wars, Renegade, Natural Selection and Savage to name a few.

**Comment by slipher** [comment]
Yeah, some other games do this... Like in Counter-Strike, if the enemy is hiding in a cloud of smoke, you can look at the cloud, and if you happen to look directly at the enemy, their presence will be revealed by the appearance of their name, and you can shoot them. I think this is stupid :stuck_out_tongue: 

I also don't favor enabling the strategy of seeing which enemy in a group is the most skilled, and targeting them first.

**Comment by DolceTriade** [comment]
I'd prefer we not show the names of the enemy team.

**Pull request closed without merging**
