### PR TITLE
Make Daemon a submodule [the real one] fix #954 #677 ref #704 #771

### PR DESCRIPTION
**Pull request by illwieckz**
It looks like to work this time.
fix #954 #677 ref #704 #771

Side note: I removed `daemon` references in `.gitignore` from the Unvanquished repository. I guess it was a rest of some previous build system. Since CMake builds in `build/` repository there is no need to ignore files named `daemon` since they are never produced in repository root anymore. Keeping this rest can produces issues since the `daemon` engine directory shares this name. I also removed the related `daemon-tty` in `.gitignore` because it's a rest too.

### CODE REVIEW

**Comment by illwieckz** [comment]
Perhaps you would have to remove `.git/modules/daemon/` on your local repositories since the old `.git/modules/libs/breapkpad` and `.git/modules/daemon/libs/recastnavigation` local conflit (they will become `.git/modules/daemon/modules/libs/breapkpad` and `.git/modules/daemon/modules/libs/recastnavigation` instead, being submodules of `.git/modules/daemon` in local storage).

**Comment by slipher** [comment]
The first three commits should probably be squashed into one to avoid creating unusable commits (although it's more convenient to review this way).

**Comment by illwieckz** [comment]
```
[illwieckz@gollum:~/dev/Unvanquished] master ± git submodule update --init --recursive
Submodule 'daemon' (https://github.com/DaemonDevelopers/Daemon.git) registered for path 'daemon'
fatal: Not a git repository: /home/illwieckz/dev/Unvanquished/daemon/../.git/modules/daemon

[illwieckz@gollum:~/dev/Unvanquished] master ± rm -Rf .git/modules/daemon

[illwieckz@gollum:~/dev/Unvanquished] master ± rm -R daemon/

[illwieckz@gollum:~/dev/Unvanquished] master ± git submodule update --init --recursive
Cloning into '/home/illwieckz/dev/Unvanquished/daemon'...
Cloning into '/home/illwieckz/dev/Unvanquished/libs/libRocket'...
Cloning into '/home/illwieckz/dev/Unvanquished/src/utils/cbse'...
Submodule path 'daemon': checked out 'b6e41f7baae75adbd7121e70d7b73b7e19ec4b6a'
Submodule 'libs/breakpad' (https://github.com/Unvanquished/breakpad.git) registered for path 'daemon/libs/breakpad'
Submodule 'libs/recastnavigation' (https://github.com/Unvanquished/recastnavigation.git) registered for path 'daemon/libs/recastnavigation'
Cloning into '/home/illwieckz/dev/Unvanquished/daemon/libs/breakpad'...
Cloning into '/home/illwieckz/dev/Unvanquished/daemon/libs/recastnavigation'...
Submodule path 'daemon/libs/breakpad': checked out '51b0082cc0b9df534f9b8f1413fb3dd82075476e'
Submodule path 'daemon/libs/recastnavigation': checked out '6b68934d6d2715501e01b1e115413cefaa0aa7d3'
Submodule path 'libs/libRocket': checked out '0e71f6b4292c85fc320944fa9c39933d76ba65e5'
Submodule path 'src/utils/cbse': checked out 'e6a9e8d4805d8f5188c430d0449524d23796c573'
```

**Comment by illwieckz** [comment]
@slipher I haven't managed to do all these step in one commit, and git does not allow me to squash them:

```
[illwieckz@gollum:~/dev/Unvanquished] master ± git rebase -i 'f369538a04574e2868bf5aa557d80fbc41a048c5'
error: The following untracked working tree files would be overwritten by checkout:
	daemon/.gitattributes
	daemon/.gitignore
	daemon/.travis.yml
	daemon/CMakeLists.txt
	daemon/COPYING.txt
	daemon/GPL.txt
	daemon/LICENSE.txt
	daemon/README.md
	[…]
	daemon/src/shared/client/cg_api.cpp
	daemon/src/shared/client/cg_api.h
	daemon/src/shared/server/sg_api.cpp
	daemon/src/shared/server/sg_api.h
	daemon/srclibs.cmake
Please move or remove them before you switch branches.
Aborting
could not detach HEAD
```

**Comment by illwieckz** [comment]
Oh I got it ! I have to remove the submodules tracked files to rebase the branch. Well, once it's reviewed I can squash them if needed.

**Comment by illwieckz** [comment]
Side note: someone can edit the description at [DaemonDevelopers/Daemon](https://github.com/DaemonDevelopers/Daemon) and set `master` as the main branch (the `daemon` one can be deleted).

**Comment by Kangz** [comment]
LGTM, made master the main branch of DaemonDevelopers/Daemon.

**Comment by illwieckz** [comment]
I squashed the first three commits, this way all commits are buildable.

**Comment by illwieckz** [comment]
So, if someone has a last word to review how the change is made, or has a strong reason to delay that change a bit more, it's time to say it. :wink:

**Comment by illwieckz** [comment]
I recall [everyone has already say OK to the idea](https://github.com/Unvanquished/Unvanquished/pull/954#issuecomment-255558136), I'm just waiting in case of there would be issues in the way it's done.

**Comment by illwieckz** [comment]
As wrote there:
https://github.com/DaemonDevelopers/Daemon/issues/3#issuecomment-279775066

The Daemon submodule path will change in the next two days (renaming the hosting organization with a better name), so I just delay the merge for two days so I will be able to rewrite my commit with the newer name before merging the engine split.

**Comment by illwieckz** [comment]
I updated the PR, the daemon submodule now points on @DaemonEngine and I updated the CBSE path too. It now just need someone to push the button.

**Comment by illwieckz** [comment]
nuclear winter is coming !

**Comment by illwieckz** [comment]
Code is now there: https://github.com/DaemonEngine/Daemon
Issues: https://github.com/DaemonEngine/Daemon/issues
PR: https://github.com/DaemonEngine/Daemon/pulls

**Comment by Kangz** [comment]
Congrats!!!

**Comment by illwieckz** [comment]
To fix your own local git repository, escaping the submodules hell:

```
cd Unvanquished/
rm -R daemon/ src/utils/cbse/
rm -Rf .git/modules/daemon/ .git/modules/src/utils/cbse/
git submodule update --init --recursive
```

**Pull request merged**
