### PR TITLE
workaround bots not able to reach armory in some cases

### PR DESCRIPTION
**Pull request by bmorel**

### CODE REVIEW

**Comment by slipher** [comment]
Can you give more detail how to reproduce the bug? I added some bots (from a recent master) with infinite funds on both Chasm and Urban, and they managed to buy weapons in both cases.

**Comment by bmorel** [comment]
Easy: just go on chasm with current default layout. There's the same on urbanp. Give human bots money and momentum, and see how they're still only using smg without armor.

**Comment by slipher** [comment]
I found an even quicker repro which is to do `bot fill 2 h` on Chasm. One of the spawning bots will immediately get stuck on the reactor. The patch fixes it, nice!

I wonder if this stuff should be in G_BotAddObstacle (where the other fudge factors are applied). But the only other use cases (besides buildings) are movers, which might be hard to test.

**Comment by bmorel** [comment]
This is simply a workaround and is destined to be remove, but the intent is to improve the situation until we get the knowledge to do that properly. Movers are currently unusable for bots anyway, so as you say, it's hard to test them. Also, I suspect the mover's code to be pretty buggy.

**Comment by slipher** [comment]
LGTM. Is there an issue about this?

**Comment by bmorel** [comment]
Not that I'm aware of.

**Pull request merged**
