### PR TITLE
fixes alien players being GIVEN the cost of their requested /class

### PR DESCRIPTION
**Pull request by cu-kai**
to be merged as a matter of urgency as this is gameplay breaking

please & thank you

### CODE REVIEW

**Comment by cu-kai** [comment]
specifically: this was broken by commit https://github.com/Unvanquished/Unvanquished/commit/54ea613c796cf8b2f4810cbe8c71e18a1e485b90

**Comment by necessarily-equal** [comment]
Merging now because this is breaking the gameplay and the fix is obviously right (and also since I did the opposite change I can attest that it wasn't intended). Thanks!

**Comment by DolceTriade** [comment]
Thanks for the fix!

**Comment by cu-kai** [comment]
Not a problem!

**Pull request merged**
